
import React from 'react';
import { Route } from "react-router-dom";
import GenericSubcategoryPage from "@/pages/categories/GenericSubcategoryPage";

export const comprehensiveSubcategoryRoutes = [
  // AI & Technology routes
  <Route key="ai" path="/ai" element={<GenericSubcategoryPage />} />,
  <Route key="ai-chatbots" path="/ai/chatbots" element={<GenericSubcategoryPage />} />,
  <Route key="ai-agents" path="/ai/agents" element={<GenericSubcategoryPage />} />,
  <Route key="ai-humanoid" path="/ai/humanoid" element={<GenericSubcategoryPage />} />,
  <Route key="ai-hr" path="/ai/hr" element={<GenericSubcategoryPage />} />,
  <Route key="ai-robots" path="/ai/robots" element={<GenericSubcategoryPage />} />,
  <Route key="ai-bots" path="/ai/bots" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech" path="/science-tech" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-knowledge" path="/science-tech/knowledge" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-inventions" path="/science-tech/inventions" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-gadgets" path="/science-tech/gadgets" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-experiments" path="/science-tech/experiments" element={<GenericSubcategoryPage />} />,
  <Route key="cell-phone" path="/cell-phone" element={<GenericSubcategoryPage />} />,
  <Route key="cell-phone-tricks" path="/cell-phone/tricks" element={<GenericSubcategoryPage />} />,
  <Route key="cell-phone-tips" path="/cell-phone/tips" element={<GenericSubcategoryPage />} />,
  <Route key="internet" path="/internet" element={<GenericSubcategoryPage />} />,
  <Route key="internet-programming" path="/internet/programming" element={<GenericSubcategoryPage />} />,
  <Route key="internet-web" path="/internet/web" element={<GenericSubcategoryPage />} />,
  <Route key="space" path="/space" element={<GenericSubcategoryPage />} />,
  <Route key="space-craft" path="/space/craft" element={<GenericSubcategoryPage />} />,
  <Route key="space-universe" path="/space/universe" element={<GenericSubcategoryPage />} />,
  <Route key="space-ufo" path="/space/ufo" element={<GenericSubcategoryPage />} />,

  // Aviation & Transport routes
  <Route key="airplanes" path="/airplanes" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-airships" path="/airplanes/airships" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-cargo" path="/airplanes/cargo" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-commercial" path="/airplanes/commercial" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-land-water" path="/airplanes/land-water" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-pilots" path="/airplanes/pilots" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-single-engine" path="/airplanes/single-engine" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-fleet" path="/airplanes/fleet" element={<GenericSubcategoryPage />} />,
  <Route key="airports" path="/airports" element={<GenericSubcategoryPage />} />,
  <Route key="airports-improvements" path="/airports/improvements" element={<GenericSubcategoryPage />} />,
  <Route key="airports-fails" path="/airports/fails" element={<GenericSubcategoryPage />} />,
  <Route key="helicopters" path="/helicopters" element={<GenericSubcategoryPage />} />,
  <Route key="helicopters-commercial" path="/helicopters/commercial" element={<GenericSubcategoryPage />} />,
  <Route key="helicopters-private" path="/helicopters/private" element={<GenericSubcategoryPage />} />,
  <Route key="cars" path="/cars" element={<GenericSubcategoryPage />} />,
  <Route key="cars-major-repairs" path="/cars/major-repairs" element={<GenericSubcategoryPage />} />,
  <Route key="cars-minor-repairs" path="/cars/minor-repairs" element={<GenericSubcategoryPage />} />,
  <Route key="cars-racing" path="/cars/racing" element={<GenericSubcategoryPage />} />,
  <Route key="cars-hacks" path="/cars/hacks" element={<GenericSubcategoryPage />} />,
  <Route key="cars-repo" path="/cars/repo" element={<GenericSubcategoryPage />} />,
  <Route key="cars-drifting" path="/cars/drifting" element={<GenericSubcategoryPage />} />,
  <Route key="cars-expensive" path="/cars/expensive" element={<GenericSubcategoryPage />} />,
  <Route key="cars-future" path="/cars/future" element={<GenericSubcategoryPage />} />,
  <Route key="cars-sedans" path="/cars/sedans" element={<GenericSubcategoryPage />} />,
  <Route key="cars-strange" path="/cars/strange" element={<GenericSubcategoryPage />} />,
  <Route key="cars-supercars" path="/cars/supercars" element={<GenericSubcategoryPage />} />,
  <Route key="cars-accidents" path="/cars/accidents" element={<GenericSubcategoryPage />} />,
  <Route key="cars-all-types" path="/cars/all-types" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles" path="/motorcycles" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-harley" path="/motorcycles/harley" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-offroad" path="/motorcycles/offroad" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-sports" path="/motorcycles/sports" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-street" path="/motorcycles/street" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-tricks" path="/motorcycles/tricks" element={<GenericSubcategoryPage />} />,
  <Route key="trucks" path="/trucks" element={<GenericSubcategoryPage />} />,
  <Route key="trucks-pickups" path="/trucks/pickups" element={<GenericSubcategoryPage />} />,
  <Route key="trucks-semi" path="/trucks/semi" element={<GenericSubcategoryPage />} />,
  <Route key="trucks-heavy-equipment" path="/trucks/heavy-equipment" element={<GenericSubcategoryPage />} />,
  <Route key="trains" path="/trains" element={<GenericSubcategoryPage />} />,
  <Route key="trains-commercial" path="/trains/commercial" element={<GenericSubcategoryPage />} />,
  <Route key="trains-passenger" path="/trains/passenger" element={<GenericSubcategoryPage />} />,
  <Route key="trains-travel" path="/trains/travel" element={<GenericSubcategoryPage />} />,
  <Route key="trains-hobos" path="/trains/hobos" element={<GenericSubcategoryPage />} />,
  <Route key="boats" path="/boats" element={<GenericSubcategoryPage />} />,
  <Route key="boats-icebreakers" path="/boats/icebreakers" element={<GenericSubcategoryPage />} />,
  <Route key="boats-cruise" path="/boats/cruise" element={<GenericSubcategoryPage />} />,
  <Route key="boats-submarines" path="/boats/submarines" element={<GenericSubcategoryPage />} />,
  <Route key="boats-tugboats" path="/boats/tugboats" element={<GenericSubcategoryPage />} />,
  <Route key="boats-yachts" path="/boats/yachts" element={<GenericSubcategoryPage />} />,
  <Route key="boats-sailing" path="/boats/sailing" element={<GenericSubcategoryPage />} />,
  <Route key="boats-jetski" path="/boats/jetski" element={<GenericSubcategoryPage />} />,
  <Route key="shipping" path="/shipping" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-ports" path="/shipping/ports" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-container" path="/shipping/container" element={<GenericSubcategoryPage />} />,

  // Animals & Nature routes
  <Route key="pets-animals" path="/pets-animals" element={<GenericSubcategoryPage />} />,
  <Route key="pets-amphibians" path="/pets-animals/amphibians" element={<GenericSubcategoryPage />} />,
  <Route key="pets-insects" path="/pets-animals/insects" element={<GenericSubcategoryPage />} />,
  <Route key="pets-birds" path="/pets-animals/birds" element={<GenericSubcategoryPage />} />,
  <Route key="pets-crustaceans" path="/pets-animals/crustaceans" element={<GenericSubcategoryPage />} />,
  <Route key="pets-fish" path="/pets-animals/fish" element={<GenericSubcategoryPage />} />,
  <Route key="pets-mammals" path="/pets-animals/mammals" element={<GenericSubcategoryPage />} />,
  <Route key="pets-marine-mammals" path="/pets-animals/marine-mammals" element={<GenericSubcategoryPage />} />,
  <Route key="pets-jellyfish" path="/pets-animals/jellyfish" element={<GenericSubcategoryPage />} />,
  <Route key="pets-reptiles" path="/pets-animals/reptiles" element={<GenericSubcategoryPage />} />,
  <Route key="pets-rodents" path="/pets-animals/rodents" element={<GenericSubcategoryPage />} />,
  <Route key="pets-cephalopods" path="/pets-animals/cephalopods" element={<GenericSubcategoryPage />} />,
  <Route key="plants" path="/plants" element={<GenericSubcategoryPage />} />,
  <Route key="plants-herbs" path="/plants/herbs" element={<GenericSubcategoryPage />} />,
  <Route key="plants-vegetables" path="/plants/vegetables" element={<GenericSubcategoryPage />} />,
  <Route key="fungi" path="/fungi" element={<GenericSubcategoryPage />} />,
  <Route key="fungi-killer" path="/fungi/killer" element={<GenericSubcategoryPage />} />,
  <Route key="fungi-edible" path="/fungi/edible" element={<GenericSubcategoryPage />} />,
  <Route key="waters" path="/waters" element={<GenericSubcategoryPage />} />,
  <Route key="waters-lakes" path="/waters/lakes" element={<GenericSubcategoryPage />} />,
  <Route key="waters-rivers" path="/waters/rivers" element={<GenericSubcategoryPage />} />,
  <Route key="waters-seas" path="/waters/seas" element={<GenericSubcategoryPage />} />,

  // Crime & Justice routes
  <Route key="courts" path="/courts" element={<GenericSubcategoryPage />} />,
  <Route key="courts-indictment" path="/courts/indictment" element={<GenericSubcategoryPage />} />,
  <Route key="courts-sentencing" path="/courts/sentencing" element={<GenericSubcategoryPage />} />,
  <Route key="courts-supreme" path="/courts/supreme" element={<GenericSubcategoryPage />} />,
  <Route key="crime" path="/crime" element={<GenericSubcategoryPage />} />,
  <Route key="crime-fraud" path="/crime/fraud" element={<GenericSubcategoryPage />} />,
  <Route key="crime-how-it-works" path="/crime/how-it-works" element={<GenericSubcategoryPage />} />,
  <Route key="crime-enterprises" path="/crime/enterprises" element={<GenericSubcategoryPage />} />,
  <Route key="crime-gangs" path="/crime/gangs" element={<GenericSubcategoryPage />} />,
  <Route key="crime-gangsters" path="/crime/gangsters" element={<GenericSubcategoryPage />} />,
  <Route key="police" path="/police" element={<GenericSubcategoryPage />} />,
  <Route key="police-chases" path="/police/chases" element={<GenericSubcategoryPage />} />,
  <Route key="police-stops" path="/police/stops" element={<GenericSubcategoryPage />} />,
  <Route key="police-sheriff" path="/police/sheriff" element={<GenericSubcategoryPage />} />,
  <Route key="jails" path="/jails" element={<GenericSubcategoryPage />} />,
  <Route key="jails-prisons" path="/jails/prisons" element={<GenericSubcategoryPage />} />,
  <Route key="jails-county" path="/jails/county" element={<GenericSubcategoryPage />} />,
  <Route key="attorneys" path="/attorneys" element={<GenericSubcategoryPage />} />,
  <Route key="attorneys-info" path="/attorneys/info" element={<GenericSubcategoryPage />} />,
  <Route key="attorneys-cases" path="/attorneys/cases" element={<GenericSubcategoryPage />} />,

  // Business & Finance routes
  <Route key="business" path="/business" element={<GenericSubcategoryPage />} />,
  <Route key="business-crypto" path="/business/crypto" element={<GenericSubcategoryPage />} />,
  <Route key="business-developments" path="/business/developments" element={<GenericSubcategoryPage />} />,
  <Route key="business-leaders" path="/business/leaders" element={<GenericSubcategoryPage />} />,
  <Route key="business-money" path="/business/money" element={<GenericSubcategoryPage />} />,
  <Route key="business-services" path="/business/services" element={<GenericSubcategoryPage />} />,
  <Route key="business-farming" path="/business/farming" element={<GenericSubcategoryPage />} />,
  <Route key="stocks" path="/stocks" element={<GenericSubcategoryPage />} />,
  <Route key="stocks-commodity" path="/stocks/commodity" element={<GenericSubcategoryPage />} />,
  <Route key="stocks-cash" path="/stocks/cash" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate" path="/real-estate" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate-residential" path="/real-estate/residential" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate-commercial" path="/real-estate/commercial" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate-luxury" path="/real-estate/luxury" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate-land" path="/real-estate/land" element={<GenericSubcategoryPage />} />,
  <Route key="advertising" path="/advertising" element={<GenericSubcategoryPage />} />,
  <Route key="advertising-tips" path="/advertising/tips" element={<GenericSubcategoryPage />} />,
  <Route key="advertising-campaigns" path="/advertising/campaigns" element={<GenericSubcategoryPage />} />,
  <Route key="food-products" path="/food-products" element={<GenericSubcategoryPage />} />,
  <Route key="food-products-business" path="/food-products/business" element={<GenericSubcategoryPage />} />,

  // Food & Drinks routes
  <Route key="foods" path="/foods" element={<GenericSubcategoryPage />} />,
  <Route key="foods-bluefin" path="/foods/bluefin" element={<GenericSubcategoryPage />} />,
  <Route key="foods-cooking" path="/foods/cooking" element={<GenericSubcategoryPage />} />,
  <Route key="foods-seafood" path="/foods/seafood" element={<GenericSubcategoryPage />} />,
  <Route key="foods-dieting" path="/foods/dieting" element={<GenericSubcategoryPage />} />,
  <Route key="foods-fruits" path="/foods/fruits" element={<GenericSubcategoryPage />} />,
  <Route key="foods-gain-weight" path="/foods/gain-weight" element={<GenericSubcategoryPage />} />,
  <Route key="foods-sweets" path="/foods/sweets" element={<GenericSubcategoryPage />} />,
  <Route key="foods-harvest" path="/foods/harvest" element={<GenericSubcategoryPage />} />,
  <Route key="foods-healthy" path="/foods/healthy" element={<GenericSubcategoryPage />} />,
  <Route key="drinks" path="/drinks" element={<GenericSubcategoryPage />} />,
  <Route key="drinks-alcohol" path="/drinks/alcohol" element={<GenericSubcategoryPage />} />,
  <Route key="drinks-non-alcohol" path="/drinks/non-alcohol" element={<GenericSubcategoryPage />} />,
  <Route key="restaurants" path="/restaurants" element={<GenericSubcategoryPage />} />,
  <Route key="restaurants-fine-dining" path="/restaurants/fine-dining" element={<GenericSubcategoryPage />} />,
  <Route key="restaurants-fast-food" path="/restaurants/fast-food" element={<GenericSubcategoryPage />} />,

  // Environment & Weather routes
  <Route key="weather" path="/weather" element={<GenericSubcategoryPage />} />,
  <Route key="weather-storms" path="/weather/storms" element={<GenericSubcategoryPage />} />,
  <Route key="weather-lightning" path="/weather/lightning" element={<GenericSubcategoryPage />} />,
  <Route key="disasters" path="/disasters" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-avalanche" path="/disasters/avalanche" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-blizzard" path="/disasters/blizzard" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-earthquakes" path="/disasters/earthquakes" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-fires" path="/disasters/fires" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-hurricanes" path="/disasters/hurricanes" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-volcano" path="/disasters/volcano" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-floods" path="/disasters/floods" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-landslide" path="/disasters/landslide" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-tornado" path="/disasters/tornado" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-tsunami" path="/disasters/tsunami" element={<GenericSubcategoryPage />} />,

  // Entertainment & Media routes
  <Route key="entertainment" path="/entertainment" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-oscars" path="/entertainment/oscars" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-actors" path="/entertainment/actors" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-late-night" path="/entertainment/late-night" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-podcasts" path="/entertainment/podcasts" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-auditions" path="/entertainment/auditions" element={<GenericSubcategoryPage />} />,
  <Route key="film" path="/film" element={<GenericSubcategoryPage />} />,
  <Route key="film-romance" path="/film/romance" element={<GenericSubcategoryPage />} />,
  <Route key="film-action" path="/film/action" element={<GenericSubcategoryPage />} />,
  <Route key="film-thriller" path="/film/thriller" element={<GenericSubcategoryPage />} />,
  <Route key="film-adventure" path="/film/adventure" element={<GenericSubcategoryPage />} />,
  <Route key="film-comedy" path="/film/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="film-drama" path="/film/drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-documentary" path="/film/documentary" element={<GenericSubcategoryPage />} />,
  <Route key="film-gangsters" path="/film/gangsters" element={<GenericSubcategoryPage />} />,
  <Route key="film-mystery" path="/film/mystery" element={<GenericSubcategoryPage />} />,
  <Route key="film-war" path="/film/war" element={<GenericSubcategoryPage />} />,
  <Route key="film-westerns" path="/film/westerns" element={<GenericSubcategoryPage />} />,
  <Route key="film-scientific" path="/film/scientific" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation" path="/film-animation" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-action" path="/film-animation/action" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-fantasy" path="/film-animation/fantasy" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-adventure" path="/film-animation/adventure" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-cartoons" path="/film-animation/cartoons" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-comedy" path="/film-animation/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-drama" path="/film-animation/drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-musical" path="/film-animation/musical" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-parody" path="/film-animation/parody" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-short" path="/film-animation/short" element={<GenericSubcategoryPage />} />,
  <Route key="tv-shows" path="/tv-shows" element={<GenericSubcategoryPage />} />,
  <Route key="tv-shows-news" path="/tv-shows/news" element={<GenericSubcategoryPage />} />,
  <Route key="tv-shows-talk" path="/tv-shows/talk" element={<GenericSubcategoryPage />} />,
  <Route key="tv-shows-court" path="/tv-shows/court" element={<GenericSubcategoryPage />} />,
  <Route key="hollywood" path="/hollywood" element={<GenericSubcategoryPage />} />,
  <Route key="hollywood-celebrities" path="/hollywood/celebrities" element={<GenericSubcategoryPage />} />,
  <Route key="hollywood-journalists" path="/hollywood/journalists" element={<GenericSubcategoryPage />} />,

  // Comedy & Funny routes
  <Route key="comedy" path="/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-standup" path="/comedy/standup" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-roasts" path="/comedy/roasts" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-snl" path="/comedy/snl" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-sitcom" path="/comedy/sitcom" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-comedians" path="/comedy/comedians" element={<GenericSubcategoryPage />} />,
  <Route key="pranks" path="/pranks" element={<GenericSubcategoryPage />} />,
  <Route key="pranks-work" path="/pranks/work" element={<GenericSubcategoryPage />} />,
  <Route key="pranks-home" path="/pranks/home" element={<GenericSubcategoryPage />} />,
  <Route key="pranks-weird" path="/pranks/weird" element={<GenericSubcategoryPage />} />,
  <Route key="funny" path="/funny" element={<GenericSubcategoryPage />} />,
  <Route key="funny-shorts" path="/funny/shorts" element={<GenericSubcategoryPage />} />,
  <Route key="funny-weird" path="/funny/weird" element={<GenericSubcategoryPage />} />,
  <Route key="funny-videos" path="/funny/videos" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers" path="/bloopers" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers-movies" path="/bloopers/movies" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers-tv" path="/bloopers/tv" element={<GenericSubcategoryPage />} />,
  <Route key="fails" path="/fails" element={<GenericSubcategoryPage />} />,
  <Route key="fails-expensive" path="/fails/expensive" element={<GenericSubcategoryPage />} />,
  <Route key="fails-people" path="/fails/people" element={<GenericSubcategoryPage />} />,
  
  // Crazy & Amazing routes
  <Route key="crazy" path="/crazy" element={<GenericSubcategoryPage />} />,
  <Route key="crazy-amazing" path="/crazy/amazing" element={<GenericSubcategoryPage />} />,
  <Route key="crazy-wouldnt-believe" path="/crazy/wouldnt-believe" element={<GenericSubcategoryPage />} />,
  
  // Comedians routes
  <Route key="comedians" path="/comedians" element={<GenericSubcategoryPage />} />,
  <Route key="comedians-interviews" path="/comedians/interviews" element={<GenericSubcategoryPage />} />,
  <Route key="comedians-specials" path="/comedians/specials" element={<GenericSubcategoryPage />} />,
  
  // Additional comedy routes
  <Route key="comedy-pranks" path="/comedy/pranks" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-jokes" path="/comedy/jokes" element={<GenericSubcategoryPage />} />,
  <Route key="funny-pranks" path="/funny/pranks" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers-screwup" path="/bloopers/screwup" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers-fails" path="/bloopers/fails" element={<GenericSubcategoryPage />} />,

  // Music routes
  <Route key="music" path="/music" element={<GenericSubcategoryPage />} />,
  <Route key="music-rock" path="/music/rock" element={<GenericSubcategoryPage />} />,
  <Route key="music-pop" path="/music/pop" element={<GenericSubcategoryPage />} />,
  <Route key="music-hip-hop" path="/music/hip-hop" element={<GenericSubcategoryPage />} />,
  <Route key="music-rap" path="/music/rap" element={<GenericSubcategoryPage />} />,
  <Route key="music-r-and-b" path="/music/r-and-b" element={<GenericSubcategoryPage />} />,
  <Route key="music-soul" path="/music/soul" element={<GenericSubcategoryPage />} />,
  <Route key="music-country" path="/music/country" element={<GenericSubcategoryPage />} />,
  <Route key="music-blues" path="/music/blues" element={<GenericSubcategoryPage />} />,
  <Route key="music-jazz" path="/music/jazz" element={<GenericSubcategoryPage />} />,
  <Route key="music-classical" path="/music/classical" element={<GenericSubcategoryPage />} />,
  <Route key="music-folk" path="/music/folk" element={<GenericSubcategoryPage />} />,
  <Route key="music-funk" path="/music/funk" element={<GenericSubcategoryPage />} />,
  <Route key="music-metal" path="/music/metal" element={<GenericSubcategoryPage />} />,
  <Route key="music-alternative" path="/music/alternative" element={<GenericSubcategoryPage />} />,
  <Route key="music-spanish" path="/music/spanish" element={<GenericSubcategoryPage />} />,
  <Route key="music-chinese" path="/music/chinese" element={<GenericSubcategoryPage />} />,
  <Route key="music-mariachi" path="/music/mariachi" element={<GenericSubcategoryPage />} />,
  <Route key="music-salsa" path="/music/salsa" element={<GenericSubcategoryPage />} />,
  <Route key="music-reggaeton" path="/music/reggaeton" element={<GenericSubcategoryPage />} />,
  <Route key="music-christian" path="/music/christian" element={<GenericSubcategoryPage />} />,
  <Route key="music-christmas" path="/music/christmas" element={<GenericSubcategoryPage />} />,
  <Route key="music-soundtracks" path="/music/soundtracks" element={<GenericSubcategoryPage />} />,
  <Route key="music-parody" path="/music/parody" element={<GenericSubcategoryPage />} />,
  <Route key="music-relaxation" path="/music/relaxation" element={<GenericSubcategoryPage />} />,
  <Route key="music-soul-train" path="/music/soul-train" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists" path="/music-artists" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists-interviews" path="/music-artists/interviews" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists-news" path="/music-artists/news" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists-works" path="/music-artists/works" element={<GenericSubcategoryPage />} />,
  <Route key="music-instruments" path="/music-instruments" element={<GenericSubcategoryPage />} />,
  <Route key="music-instruments-guitar" path="/music-instruments/guitar" element={<GenericSubcategoryPage />} />,
  <Route key="music-instruments-piano" path="/music-instruments/piano" element={<GenericSubcategoryPage />} />,
  <Route key="dances" path="/dances" element={<GenericSubcategoryPage />} />,
  <Route key="dances-styles" path="/dances/styles" element={<GenericSubcategoryPage />} />,
  <Route key="dances-choreography" path="/dances/choreography" element={<GenericSubcategoryPage />} />,

  // Gaming & Hobbies routes
  <Route key="gaming" path="/gaming" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-arcade" path="/gaming/arcade" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-casino" path="/gaming/casino" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-dominos" path="/gaming/dominos" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-lottery" path="/gaming/lottery" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-console" path="/gaming/console" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-cards" path="/gaming/cards" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-challenges" path="/gaming/challenges" element={<GenericSubcategoryPage />} />,
  <Route key="magic-tricks" path="/magic-tricks" element={<GenericSubcategoryPage />} />,
  <Route key="magic-tricks-illusions" path="/magic-tricks/illusions" element={<GenericSubcategoryPage />} />,
  <Route key="magic-tricks-street" path="/magic-tricks/street" element={<GenericSubcategoryPage />} />,
  <Route key="toys" path="/toys" element={<GenericSubcategoryPage />} />,
  <Route key="toys-rockets" path="/toys/rockets" element={<GenericSubcategoryPage />} />,
  <Route key="toys-rc" path="/toys/rc" element={<GenericSubcategoryPage />} />,
  <Route key="riddles" path="/riddles" element={<GenericSubcategoryPage />} />,
  <Route key="riddles-puzzles" path="/riddles/puzzles" element={<GenericSubcategoryPage />} />,

  // Fitness & Health routes
  <Route key="physical-fitness" path="/physical-fitness" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-calisthenics" path="/physical-fitness/calisthenics" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-weight-lifting" path="/physical-fitness/weight-lifting" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-weightlifting-female" path="/physical-fitness/weightlifting-female" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-weightlifting-male" path="/physical-fitness/weightlifting-male" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-workout" path="/physical-fitness/workout" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-workout-female" path="/physical-fitness/workout-female" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-workout-male" path="/physical-fitness/workout-male" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-yoga" path="/physical-fitness/yoga" element={<GenericSubcategoryPage />} />,
  <Route key="martial-arts" path="/martial-arts" element={<GenericSubcategoryPage />} />,
  <Route key="martial-arts-self-defense" path="/martial-arts/self-defense" element={<GenericSubcategoryPage />} />,
  <Route key="martial-arts-mma" path="/martial-arts/mma" element={<GenericSubcategoryPage />} />,
  <Route key="swimming" path="/swimming" element={<GenericSubcategoryPage />} />,
  <Route key="swimming-diving" path="/swimming/diving" element={<GenericSubcategoryPage />} />,
  <Route key="swimming-laps" path="/swimming/laps" element={<GenericSubcategoryPage />} />,
  <Route key="hair-beauty" path="/hair-beauty" element={<GenericSubcategoryPage />} />,
  <Route key="hair-beauty-cuts" path="/hair-beauty/cuts" element={<GenericSubcategoryPage />} />,
  <Route key="hair-beauty-styles" path="/hair-beauty/styles" element={<GenericSubcategoryPage />} />,
  <Route key="hair-beauty-extensions" path="/hair-beauty/extensions" element={<GenericSubcategoryPage />} />,
  <Route key="cosmetics" path="/cosmetics" element={<GenericSubcategoryPage />} />,
  <Route key="cosmetics-eyelashes" path="/cosmetics/eyelashes" element={<GenericSubcategoryPage />} />,
  <Route key="cosmetics-foundation" path="/cosmetics/foundation" element={<GenericSubcategoryPage />} />,
  <Route key="cosmetics-lipstick" path="/cosmetics/lipstick" element={<GenericSubcategoryPage />} />,

  // Models & Photos routes
  <Route key="models" path="/models" element={<GenericSubcategoryPage />} />,
  <Route key="models-fashion" path="/models/fashion" element={<GenericSubcategoryPage />} />,
  <Route key="models-female-male" path="/models/female-male" element={<GenericSubcategoryPage />} />,
  <Route key="models-fit" path="/models/fit" element={<GenericSubcategoryPage />} />,
  <Route key="models-mature" path="/models/mature" element={<GenericSubcategoryPage />} />,
  <Route key="models-plus-size" path="/models/plus-size" element={<GenericSubcategoryPage />} />,
  <Route key="models-seasonal" path="/models/seasonal" element={<GenericSubcategoryPage />} />,
  <Route key="models-swimsuit" path="/models/swimsuit" element={<GenericSubcategoryPage />} />,
  <Route key="models-winter" path="/models/winter" element={<GenericSubcategoryPage />} />,
  <Route key="models-summer" path="/models/summer" element={<GenericSubcategoryPage />} />,
  <Route key="models-fall" path="/models/fall" element={<GenericSubcategoryPage />} />,
  <Route key="pictures" path="/pictures" element={<GenericSubcategoryPage />} />,
  <Route key="pictures-photos" path="/pictures/photos" element={<GenericSubcategoryPage />} />,
  <Route key="pictures-art" path="/pictures/art" element={<GenericSubcategoryPage />} />,

  // Travel & Places routes
  <Route key="travel" path="/travel" element={<GenericSubcategoryPage />} />,
  <Route key="travel-beaches" path="/travel/beaches" element={<GenericSubcategoryPage />} />,
  <Route key="travel-cities" path="/travel/cities" element={<GenericSubcategoryPage />} />,
  <Route key="travel-foods" path="/travel/foods" element={<GenericSubcategoryPage />} />,
  <Route key="travel-hotels" path="/travel/hotels" element={<GenericSubcategoryPage />} />,
  <Route key="travel-luxury-hotels" path="/travel/luxury-hotels" element={<GenericSubcategoryPage />} />,
  <Route key="travel-unique-hotels" path="/travel/unique-hotels" element={<GenericSubcategoryPage />} />,
  <Route key="travel-nightclubs" path="/travel/nightclubs" element={<GenericSubcategoryPage />} />,
  <Route key="travel-restaurants" path="/travel/restaurants" element={<GenericSubcategoryPage />} />,
  <Route key="travel-street-food" path="/travel/street-food" element={<GenericSubcategoryPage />} />,
  <Route key="travel-streets" path="/travel/streets" element={<GenericSubcategoryPage />} />,
  <Route key="travel-new-year" path="/travel/new-year" element={<GenericSubcategoryPage />} />,
  <Route key="travel-tips" path="/travel/tips" element={<GenericSubcategoryPage />} />,

  // How-To & Education routes
  <Route key="howto" path="/howto" element={<GenericSubcategoryPage />} />,
  <Route key="howto-building" path="/howto/building" element={<GenericSubcategoryPage />} />,
  <Route key="howto-cleaning" path="/howto/cleaning" element={<GenericSubcategoryPage />} />,
  <Route key="howto-bathroom" path="/howto/bathroom" element={<GenericSubcategoryPage />} />,
  <Route key="howto-windows" path="/howto/windows" element={<GenericSubcategoryPage />} />,
  <Route key="howto-toilets" path="/howto/toilets" element={<GenericSubcategoryPage />} />,
  <Route key="howto-electrical" path="/howto/electrical" element={<GenericSubcategoryPage />} />,
  <Route key="howto-arts-crafts" path="/howto/arts-crafts" element={<GenericSubcategoryPage />} />,
  <Route key="education" path="/education" element={<GenericSubcategoryPage />} />,
  <Route key="education-anatomy" path="/education/anatomy" element={<GenericSubcategoryPage />} />,
  <Route key="education-countries" path="/education/countries" element={<GenericSubcategoryPage />} />,
  <Route key="education-immigration" path="/education/immigration" element={<GenericSubcategoryPage />} />,
  <Route key="education-geography" path="/education/geography" element={<GenericSubcategoryPage />} />,
  <Route key="education-laws" path="/education/laws" element={<GenericSubcategoryPage />} />,
  <Route key="education-medicine" path="/education/medicine" element={<GenericSubcategoryPage />} />,
  <Route key="education-religion" path="/education/religion" element={<GenericSubcategoryPage />} />,
  <Route key="education-nursing" path="/education/nursing" element={<GenericSubcategoryPage />} />,
  <Route key="education-learning" path="/education/learning" element={<GenericSubcategoryPage />} />,
  <Route key="kids" path="/kids" element={<GenericSubcategoryPage />} />,
  <Route key="kids-beauty" path="/kids/beauty" element={<GenericSubcategoryPage />} />,
  <Route key="kids-cartoons" path="/kids/cartoons" element={<GenericSubcategoryPage />} />,
  <Route key="kids-education" path="/kids/education" element={<GenericSubcategoryPage />} />,
  <Route key="kids-funny" path="/kids/funny" element={<GenericSubcategoryPage />} />,
  <Route key="kids-oceanography" path="/kids/oceanography" element={<GenericSubcategoryPage />} />,
  <Route key="kids-animals" path="/kids/animals" element={<GenericSubcategoryPage />} />,
  <Route key="kids-animation" path="/kids/animation" element={<GenericSubcategoryPage />} />,
  <Route key="kids-alphabets" path="/kids/alphabets" element={<GenericSubcategoryPage />} />,
  <Route key="kids-colors" path="/kids/colors" element={<GenericSubcategoryPage />} />,
  <Route key="kids-foods" path="/kids/foods" element={<GenericSubcategoryPage />} />,
  <Route key="kids-math" path="/kids/math" element={<GenericSubcategoryPage />} />,
  <Route key="kids-reading" path="/kids/reading" element={<GenericSubcategoryPage />} />,
  <Route key="kids-films" path="/kids/films" element={<GenericSubcategoryPage />} />,
  <Route key="kids-games" path="/kids/games" element={<GenericSubcategoryPage />} />,
  <Route key="kids-music" path="/kids/music" element={<GenericSubcategoryPage />} />,
  <Route key="kids-videos" path="/kids/videos" element={<GenericSubcategoryPage />} />,

  // People & Workers routes
  <Route key="people" path="/people" element={<GenericSubcategoryPage />} />,
  <Route key="people-bigotry" path="/people/bigotry" element={<GenericSubcategoryPage />} />,
  <Route key="people-fighting" path="/people/fighting" element={<GenericSubcategoryPage />} />,
  <Route key="people-karma" path="/people/karma" element={<GenericSubcategoryPage />} />,
  <Route key="people-lookalikes" path="/people/lookalikes" element={<GenericSubcategoryPage />} />,
  <Route key="people-thefts" path="/people/thefts" element={<GenericSubcategoryPage />} />,
  <Route key="people-amazing" path="/people/amazing" element={<GenericSubcategoryPage />} />,
  <Route key="people-fails" path="/people/fails" element={<GenericSubcategoryPage />} />,
  <Route key="workers" path="/workers" element={<GenericSubcategoryPage />} />,
  <Route key="workers-fails" path="/workers/fails" element={<GenericSubcategoryPage />} />,
  <Route key="workers-amazing" path="/workers/amazing" element={<GenericSubcategoryPage />} />,
  <Route key="babies" path="/babies" element={<GenericSubcategoryPage />} />,
  <Route key="babies-funny" path="/babies/funny" element={<GenericSubcategoryPage />} />,
  <Route key="babies-cute" path="/babies/cute" element={<GenericSubcategoryPage />} />,
  <Route key="speeches" path="/speeches" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-commencement" path="/speeches/commencement" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-eulogy" path="/speeches/eulogy" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-informative" path="/speeches/informative" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-motivational" path="/speeches/motivational" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-persuasive" path="/speeches/persuasive" element={<GenericSubcategoryPage />} />,
  <Route key="motivation" path="/motivation" element={<GenericSubcategoryPage />} />,
  <Route key="motivation-self" path="/motivation/self" element={<GenericSubcategoryPage />} />,
  <Route key="success" path="/success" element={<GenericSubcategoryPage />} />,
  <Route key="success-stories" path="/success/stories" element={<GenericSubcategoryPage />} />,

  // Sports Extended routes
  <Route key="sports" path="/sports" element={<GenericSubcategoryPage />} />,
  <Route key="sports-arenas" path="/sports/arenas" element={<GenericSubcategoryPage />} />,
  <Route key="sports-basketball" path="/sports/basketball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-car-racing" path="/sports/car-racing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-comedy" path="/sports/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="sports-fishing" path="/sports/fishing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-interviews" path="/sports/interviews" element={<GenericSubcategoryPage />} />,
  <Route key="sports-kickboxing" path="/sports/kickboxing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mlb" path="/sports/mlb" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nba" path="/sports/nba" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nfl" path="/sports/nfl" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl" path="/sports/nhl" element={<GenericSubcategoryPage />} />,
  <Route key="sports-pga" path="/sports/pga" element={<GenericSubcategoryPage />} />,
  <Route key="sports-race-car" path="/sports/race-car" element={<GenericSubcategoryPage />} />,
  <Route key="sports-cycling" path="/sports/cycling" element={<GenericSubcategoryPage />} />,
  <Route key="sports-rugby" path="/sports/rugby" element={<GenericSubcategoryPage />} />,
  <Route key="sports-soccer" path="/sports/soccer" element={<GenericSubcategoryPage />} />,
  <Route key="sports-surfing" path="/sports/surfing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-tennis-men" path="/sports/tennis-men" element={<GenericSubcategoryPage />} />,
  <Route key="sports-tennis-women" path="/sports/tennis-women" element={<GenericSubcategoryPage />} />,
  <Route key="sports-track-field" path="/sports/track-field" element={<GenericSubcategoryPage />} />,
  <Route key="sports-volleyball" path="/sports/volleyball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-weightlifting" path="/sports/weightlifting" element={<GenericSubcategoryPage />} />,
  <Route key="sports-wwe" path="/sports/wwe" element={<GenericSubcategoryPage />} />,
  <Route key="sports-boxing" path="/sports/boxing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-boxing-interviews" path="/sports/boxing-interviews" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college" path="/sports/college" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-baseball" path="/sports/college-baseball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-basketball" path="/sports/college-basketball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-football" path="/sports/college-football" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-track" path="/sports/college-track" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-women-basketball" path="/sports/college-women-basketball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-fan-challenges" path="/sports/fan-challenges" element={<GenericSubcategoryPage />} />,
  <Route key="sports-high-school" path="/sports/high-school" element={<GenericSubcategoryPage />} />,
  <Route key="sports-formula-one" path="/sports/formula-one" element={<GenericSubcategoryPage />} />,
  <Route key="sports-golf-ryder" path="/sports/golf-ryder" element={<GenericSubcategoryPage />} />,
  <Route key="sports-country-hockey" path="/sports/country-hockey" element={<GenericSubcategoryPage />} />,
  <Route key="sports-horse-racing" path="/sports/horse-racing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-equestrian" path="/sports/equestrian" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mlb-playoffs" path="/sports/mlb-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-world-series" path="/sports/world-series" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mls" path="/sports/mls" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mma" path="/sports/mma" element={<GenericSubcategoryPage />} />,
  <Route key="sports-superbike" path="/sports/superbike" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nascar" path="/sports/nascar" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nba-playoffs" path="/sports/nba-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nfl-superbowl" path="/sports/nfl-superbowl" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl-playoffs" path="/sports/nhl-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl-allstar" path="/sports/nhl-allstar" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhra" path="/sports/nhra" element={<GenericSubcategoryPage />} />,
  <Route key="sports-olympics" path="/sports/olympics" element={<GenericSubcategoryPage />} />,
  <Route key="sports-personalities" path="/sports/personalities" element={<GenericSubcategoryPage />} />,
  <Route key="sports-pro-golf" path="/sports/pro-golf" element={<GenericSubcategoryPage />} />,
  <Route key="sports-beach-volleyball" path="/sports/beach-volleyball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-pro-volleyball" path="/sports/pro-volleyball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-wnba" path="/sports/wnba" element={<GenericSubcategoryPage />} />,
  <Route key="sports-wnba-playoffs" path="/sports/wnba-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-women-mma" path="/sports/women-mma" element={<GenericSubcategoryPage />} />,
  <Route key="sports-news" path="/sports/news" element={<GenericSubcategoryPage />} />,

  // History & Artifacts routes
  <Route key="history" path="/history" element={<GenericSubcategoryPage />} />,
  <Route key="history-american" path="/history/american" element={<GenericSubcategoryPage />} />,
  <Route key="history-biblical" path="/history/biblical" element={<GenericSubcategoryPage />} />,
  <Route key="history-world" path="/history/world" element={<GenericSubcategoryPage />} />,
  <Route key="artifacts" path="/artifacts" element={<GenericSubcategoryPage />} />,
  <Route key="artifacts-antiques" path="/artifacts/antiques" element={<GenericSubcategoryPage />} />,
  <Route key="artifacts-colosseum" path="/artifacts/colosseum" element={<GenericSubcategoryPage />} />,
  <Route key="statues" path="/statues" element={<GenericSubcategoryPage />} />,
  <Route key="statues-sculptures" path="/statues/sculptures" element={<GenericSubcategoryPage />} />,
  <Route key="statues-carvers" path="/statues/carvers" element={<GenericSubcategoryPage />} />,
  <Route key="bible" path="/bible" element={<GenericSubcategoryPage />} />,
  <Route key="bible-quotes" path="/bible/quotes" element={<GenericSubcategoryPage />} />,
  <Route key="bible-scriptures" path="/bible/scriptures" element={<GenericSubcategoryPage />} />,

  // Government & Politics routes
  <Route key="government" path="/government" element={<GenericSubcategoryPage />} />,
  <Route key="government-senate" path="/government/senate" element={<GenericSubcategoryPage />} />,
  <Route key="government-house" path="/government/house" element={<GenericSubcategoryPage />} />,
  <Route key="presidents" path="/presidents" element={<GenericSubcategoryPage />} />,
  <Route key="presidents-motorcade" path="/presidents/motorcade" element={<GenericSubcategoryPage />} />,
  <Route key="presidents-airforce" path="/presidents/airforce" element={<GenericSubcategoryPage />} />,
  <Route key="presidents-former" path="/presidents/former" element={<GenericSubcategoryPage />} />,
  <Route key="politics" path="/politics" element={<GenericSubcategoryPage />} />,
  <Route key="politics-news" path="/politics/news" element={<GenericSubcategoryPage />} />,
  <Route key="politics-podcasts" path="/politics/podcasts" element={<GenericSubcategoryPage />} />,
  <Route key="protesters" path="/protesters" element={<GenericSubcategoryPage />} />,
  <Route key="protesters-demonstrations" path="/protesters/demonstrations" element={<GenericSubcategoryPage />} />,
  <Route key="military" path="/military" element={<GenericSubcategoryPage />} />,
  <Route key="military-pilots" path="/military/pilots" element={<GenericSubcategoryPage />} />,
  <Route key="military-reserves" path="/military/reserves" element={<GenericSubcategoryPage />} />,
  <Route key="military-weapons" path="/military/weapons" element={<GenericSubcategoryPage />} />,
  <Route key="military-aircrafts" path="/military/aircrafts" element={<GenericSubcategoryPage />} />,
  <Route key="military-documentary" path="/military/documentary" element={<GenericSubcategoryPage />} />,
  <Route key="military-ships" path="/military/ships" element={<GenericSubcategoryPage />} />,
  <Route key="military-submarines" path="/military/submarines" element={<GenericSubcategoryPage />} />,
  <Route key="military-war" path="/military/war" element={<GenericSubcategoryPage />} />,
  <Route key="military-drones" path="/military/drones" element={<GenericSubcategoryPage />} />,
  <Route key="military-personnel" path="/military/personnel" element={<GenericSubcategoryPage />} />,
  <Route key="weapons" path="/weapons" element={<GenericSubcategoryPage />} />,
  <Route key="weapons-civilian" path="/weapons/civilian" element={<GenericSubcategoryPage />} />,

  // Lifestyle routes
  <Route key="relationships" path="/relationships" element={<GenericSubcategoryPage />} />,
  <Route key="relationships-divorce" path="/relationships/divorce" element={<GenericSubcategoryPage />} />,
  <Route key="relationships-love" path="/relationships/love" element={<GenericSubcategoryPage />} />,
  <Route key="relationships-marriage" path="/relationships/marriage" element={<GenericSubcategoryPage />} />,
  <Route key="dating" path="/dating" element={<GenericSubcategoryPage />} />,
  <Route key="dating-flirting" path="/dating/flirting" element={<GenericSubcategoryPage />} />,
  <Route key="dating-breakups" path="/dating/breakups" element={<GenericSubcategoryPage />} />,
  <Route key="dating-tips" path="/dating/tips" element={<GenericSubcategoryPage />} />,
  <Route key="dating-single" path="/dating/single" element={<GenericSubcategoryPage />} />,
  <Route key="dating-attraction" path="/dating/attraction" element={<GenericSubcategoryPage />} />,
  <Route key="intimacy" path="/intimacy" element={<GenericSubcategoryPage />} />,
  <Route key="intimacy-relationships" path="/intimacy/relationships" element={<GenericSubcategoryPage />} />,
  <Route key="ideology" path="/ideology" element={<GenericSubcategoryPage />} />,
  <Route key="ideology-lifestyles" path="/ideology/lifestyles" element={<GenericSubcategoryPage />} />,

  // Documentaries & Drugs routes
  <Route key="documentaries" path="/documentaries" element={<GenericSubcategoryPage />} />,
  <Route key="documentaries-drugs" path="/documentaries/drugs" element={<GenericSubcategoryPage />} />,
  <Route key="documentaries-real-events" path="/documentaries/real-events" element={<GenericSubcategoryPage />} />,
  <Route key="drugs" path="/drugs" element={<GenericSubcategoryPage />} />,
  <Route key="drugs-dealers" path="/drugs/dealers" element={<GenericSubcategoryPage />} />,
  <Route key="drugs-addiction" path="/drugs/addiction" element={<GenericSubcategoryPage />} />,

  // Quotes & Poems routes
  <Route key="quotes" path="/quotes" element={<GenericSubcategoryPage />} />,
  <Route key="quotes-poems" path="/quotes/poems" element={<GenericSubcategoryPage />} />,
  <Route key="quotes-statements" path="/quotes/statements" element={<GenericSubcategoryPage />} />,

  // Radio routes
  <Route key="radio" path="/radio" element={<GenericSubcategoryPage />} />,
  <Route key="radio-music" path="/radio/music" element={<GenericSubcategoryPage />} />,
  <Route key="radio-podcast" path="/radio/podcast" element={<GenericSubcategoryPage />} />,
  <Route key="radio-rc" path="/radio/rc" element={<GenericSubcategoryPage />} />,
  <Route key="radio-shows" path="/radio/shows" element={<GenericSubcategoryPage />} />,

  // Moments routes
  <Route key="moments" path="/moments" element={<GenericSubcategoryPage />} />,
  <Route key="moments-special" path="/moments/special" element={<GenericSubcategoryPage />} />,
  <Route key="moments-good-bad" path="/moments/good-bad" element={<GenericSubcategoryPage />} />,

  // Drones routes
  <Route key="drones" path="/drones" element={<GenericSubcategoryPage />} />,
  <Route key="drones-civilian" path="/drones/civilian" element={<GenericSubcategoryPage />} />,
  <Route key="drones-recreational" path="/drones/recreational" element={<GenericSubcategoryPage />} />,

  // Animation routes (separate from film-animation)
  <Route key="animation" path="/animation" element={<GenericSubcategoryPage />} />,
  <Route key="animation-action" path="/animation/action" element={<GenericSubcategoryPage />} />,
  <Route key="animation-fantasy" path="/animation/fantasy" element={<GenericSubcategoryPage />} />,
  <Route key="animation-adventure" path="/animation/adventure" element={<GenericSubcategoryPage />} />,
  <Route key="animation-cartoons" path="/animation/cartoons" element={<GenericSubcategoryPage />} />,
  <Route key="animation-comedy" path="/animation/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="animation-drama" path="/animation/drama" element={<GenericSubcategoryPage />} />,
  <Route key="animation-musical" path="/animation/musical" element={<GenericSubcategoryPage />} />,
  <Route key="animation-parody" path="/animation/parody" element={<GenericSubcategoryPage />} />,
  <Route key="animation-short" path="/animation/short" element={<GenericSubcategoryPage />} />,

  // Additional Film routes
  <Route key="film-action-crime" path="/film/action-crime" element={<GenericSubcategoryPage />} />,
  <Route key="film-comedy-drama" path="/film/comedy-drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-crime-drama" path="/film/crime-drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-clips" path="/film/clips" element={<GenericSubcategoryPage />} />,

  // Additional Entertainment routes
  <Route key="entertainment-podcast" path="/entertainment/podcast" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-hollywood" path="/entertainment/hollywood" element={<GenericSubcategoryPage />} />,
];
