
import React from 'react';
import { Route } from "react-router-dom";
import GenericSubcategoryPage from "@/pages/categories/GenericSubcategoryPage";

export const comprehensiveSubcategoryRoutes = [
  // AI & Technology routes (nested and flat for search)
  <Route key="ai" path="/ai" element={<GenericSubcategoryPage />} />,
  <Route key="ai-chatbots" path="/ai/chatbots" element={<GenericSubcategoryPage />} />,
  <Route key="ai-agents" path="/ai/agents" element={<GenericSubcategoryPage />} />,
  <Route key="ai-agents-software" path="/ai-agents-software" element={<GenericSubcategoryPage />} />,
  <Route key="ai-chatgpt-gemini" path="/ai-chatgpt-gemini" element={<GenericSubcategoryPage />} />,
  <Route key="ai-bots-automation" path="/ai-bots-automation" element={<GenericSubcategoryPage />} />,
  <Route key="ai-human-resources" path="/ai-human-resources" element={<GenericSubcategoryPage />} />,
  <Route key="ai-humanoids" path="/ai-humanoids" element={<GenericSubcategoryPage />} />,
  <Route key="ai-robotics" path="/ai-robotics" element={<GenericSubcategoryPage />} />,
  <Route key="ai-humanoid" path="/ai/humanoid" element={<GenericSubcategoryPage />} />,
  <Route key="ai-hr" path="/ai/hr" element={<GenericSubcategoryPage />} />,
  <Route key="ai-robots" path="/ai/robots" element={<GenericSubcategoryPage />} />,
  <Route key="ai-bots" path="/ai/bots" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech" path="/science-tech" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-knowledge" path="/science-tech/knowledge" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-inventions" path="/science-tech/inventions" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-gadgets" path="/science-tech/gadgets" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-experiments" path="/science-tech/experiments" element={<GenericSubcategoryPage />} />,
  <Route key="science-technology" path="/science-technology" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-inventions-flat" path="/science-tech-inventions" element={<GenericSubcategoryPage />} />,
  <Route key="science-tech-gadgets-flat" path="/science-tech-gadgets" element={<GenericSubcategoryPage />} />,
  <Route key="cell-phone" path="/cell-phone" element={<GenericSubcategoryPage />} />,
  <Route key="cell-phone-tricks" path="/cell-phone/tricks" element={<GenericSubcategoryPage />} />,
  <Route key="cell-phone-tips" path="/cell-phone/tips" element={<GenericSubcategoryPage />} />,
  <Route key="cell-phone-tricks-flat" path="/cell-phone-tricks" element={<GenericSubcategoryPage />} />,
  <Route key="internet" path="/internet" element={<GenericSubcategoryPage />} />,
  <Route key="internet-programming" path="/internet/programming" element={<GenericSubcategoryPage />} />,
  <Route key="internet-web" path="/internet/web" element={<GenericSubcategoryPage />} />,
  <Route key="internet-programming-flat" path="/internet-programming" element={<GenericSubcategoryPage />} />,
  <Route key="space" path="/space" element={<GenericSubcategoryPage />} />,
  <Route key="space-craft" path="/space/craft" element={<GenericSubcategoryPage />} />,
  <Route key="space-universe" path="/space/universe" element={<GenericSubcategoryPage />} />,
  <Route key="space-ufo" path="/space/ufo" element={<GenericSubcategoryPage />} />,

  // Aviation & Transport routes
  <Route key="airplanes" path="/airplanes" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-airships" path="/airplanes/airships" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-cargo" path="/airplanes/cargo" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-commercial" path="/airplanes/commercial" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-land-water" path="/airplanes/land-water" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-pilots" path="/airplanes/pilots" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-single-engine" path="/airplanes/single-engine" element={<GenericSubcategoryPage />} />,
  <Route key="airplanes-fleet" path="/airplanes/fleet" element={<GenericSubcategoryPage />} />,
  <Route key="airports" path="/airports" element={<GenericSubcategoryPage />} />,
  <Route key="airports-improvements" path="/airports/improvements" element={<GenericSubcategoryPage />} />,
  <Route key="airports-fails" path="/airports/fails" element={<GenericSubcategoryPage />} />,
  <Route key="helicopters" path="/helicopters" element={<GenericSubcategoryPage />} />,
  <Route key="helicopters-commercial" path="/helicopters/commercial" element={<GenericSubcategoryPage />} />,
  <Route key="helicopters-private" path="/helicopters/private" element={<GenericSubcategoryPage />} />,
  <Route key="cars" path="/cars" element={<GenericSubcategoryPage />} />,
  <Route key="cars-major-repairs" path="/cars/major-repairs" element={<GenericSubcategoryPage />} />,
  <Route key="cars-minor-repairs" path="/cars/minor-repairs" element={<GenericSubcategoryPage />} />,
  <Route key="cars-racing" path="/cars/racing" element={<GenericSubcategoryPage />} />,
  <Route key="cars-hacks" path="/cars/hacks" element={<GenericSubcategoryPage />} />,
  <Route key="cars-repo" path="/cars/repo" element={<GenericSubcategoryPage />} />,
  <Route key="cars-drifting" path="/cars/drifting" element={<GenericSubcategoryPage />} />,
  <Route key="cars-expensive" path="/cars/expensive" element={<GenericSubcategoryPage />} />,
  <Route key="cars-future" path="/cars/future" element={<GenericSubcategoryPage />} />,
  <Route key="cars-sedans" path="/cars/sedans" element={<GenericSubcategoryPage />} />,
  <Route key="cars-strange" path="/cars/strange" element={<GenericSubcategoryPage />} />,
  <Route key="cars-supercars" path="/cars/supercars" element={<GenericSubcategoryPage />} />,
  <Route key="cars-accidents" path="/cars/accidents" element={<GenericSubcategoryPage />} />,
  <Route key="cars-all-types" path="/cars/all-types" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles" path="/motorcycles" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-harley" path="/motorcycles/harley" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-offroad" path="/motorcycles/offroad" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-sports" path="/motorcycles/sports" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-street" path="/motorcycles/street" element={<GenericSubcategoryPage />} />,
  <Route key="motorcycles-tricks" path="/motorcycles/tricks" element={<GenericSubcategoryPage />} />,
  <Route key="trucks" path="/trucks" element={<GenericSubcategoryPage />} />,
  <Route key="trucks-pickups" path="/trucks/pickups" element={<GenericSubcategoryPage />} />,
  <Route key="trucks-semi" path="/trucks/semi" element={<GenericSubcategoryPage />} />,
  <Route key="trucks-heavy-equipment" path="/trucks/heavy-equipment" element={<GenericSubcategoryPage />} />,
  <Route key="trains" path="/trains" element={<GenericSubcategoryPage />} />,
  <Route key="trains-commercial" path="/trains/commercial" element={<GenericSubcategoryPage />} />,
  <Route key="trains-passenger" path="/trains/passenger" element={<GenericSubcategoryPage />} />,
  <Route key="trains-travel" path="/trains/travel" element={<GenericSubcategoryPage />} />,
  <Route key="trains-hobos" path="/trains/hobos" element={<GenericSubcategoryPage />} />,
  <Route key="boats" path="/boats" element={<GenericSubcategoryPage />} />,
  <Route key="boats-icebreakers" path="/boats/icebreakers" element={<GenericSubcategoryPage />} />,
  <Route key="boats-cruise" path="/boats/cruise" element={<GenericSubcategoryPage />} />,
  <Route key="boats-submarines" path="/boats/submarines" element={<GenericSubcategoryPage />} />,
  <Route key="boats-tugboats" path="/boats/tugboats" element={<GenericSubcategoryPage />} />,
  <Route key="boats-yachts" path="/boats/yachts" element={<GenericSubcategoryPage />} />,
  <Route key="boats-sailing" path="/boats/sailing" element={<GenericSubcategoryPage />} />,
  <Route key="boats-jetski" path="/boats/jetski" element={<GenericSubcategoryPage />} />,
  <Route key="shipping" path="/shipping" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-ports" path="/shipping/ports" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-container" path="/shipping/container" element={<GenericSubcategoryPage />} />,

  // Animals & Nature routes
  <Route key="pets-animals" path="/pets-animals" element={<GenericSubcategoryPage />} />,
  <Route key="pets-amphibians" path="/pets-animals/amphibians" element={<GenericSubcategoryPage />} />,
  <Route key="pets-insects" path="/pets-animals/insects" element={<GenericSubcategoryPage />} />,
  <Route key="pets-birds" path="/pets-animals/birds" element={<GenericSubcategoryPage />} />,
  <Route key="pets-crustaceans" path="/pets-animals/crustaceans" element={<GenericSubcategoryPage />} />,
  <Route key="pets-fish" path="/pets-animals/fish" element={<GenericSubcategoryPage />} />,
  <Route key="pets-mammals" path="/pets-animals/mammals" element={<GenericSubcategoryPage />} />,
  <Route key="pets-marine-mammals" path="/pets-animals/marine-mammals" element={<GenericSubcategoryPage />} />,
  <Route key="pets-jellyfish" path="/pets-animals/jellyfish" element={<GenericSubcategoryPage />} />,
  <Route key="pets-reptiles" path="/pets-animals/reptiles" element={<GenericSubcategoryPage />} />,
  <Route key="pets-rodents" path="/pets-animals/rodents" element={<GenericSubcategoryPage />} />,
  <Route key="pets-cephalopods" path="/pets-animals/cephalopods" element={<GenericSubcategoryPage />} />,
  <Route key="plants" path="/plants" element={<GenericSubcategoryPage />} />,
  <Route key="plants-herbs" path="/plants/herbs" element={<GenericSubcategoryPage />} />,
  <Route key="plants-vegetables" path="/plants/vegetables" element={<GenericSubcategoryPage />} />,
  <Route key="fungi" path="/fungi" element={<GenericSubcategoryPage />} />,
  <Route key="fungi-killer" path="/fungi/killer" element={<GenericSubcategoryPage />} />,
  <Route key="fungi-edible" path="/fungi/edible" element={<GenericSubcategoryPage />} />,
  <Route key="waters" path="/waters" element={<GenericSubcategoryPage />} />,
  <Route key="waters-lakes" path="/waters/lakes" element={<GenericSubcategoryPage />} />,
  <Route key="waters-rivers" path="/waters/rivers" element={<GenericSubcategoryPage />} />,
  <Route key="waters-seas" path="/waters/seas" element={<GenericSubcategoryPage />} />,

  // Crime & Justice routes
  <Route key="courts" path="/courts" element={<GenericSubcategoryPage />} />,
  <Route key="courts-indictment" path="/courts/indictment" element={<GenericSubcategoryPage />} />,
  <Route key="courts-sentencing" path="/courts/sentencing" element={<GenericSubcategoryPage />} />,
  <Route key="courts-supreme" path="/courts/supreme" element={<GenericSubcategoryPage />} />,
  <Route key="crime" path="/crime" element={<GenericSubcategoryPage />} />,
  <Route key="crime-fraud" path="/crime/fraud" element={<GenericSubcategoryPage />} />,
  <Route key="crime-how-it-works" path="/crime/how-it-works" element={<GenericSubcategoryPage />} />,
  <Route key="crime-enterprises" path="/crime/enterprises" element={<GenericSubcategoryPage />} />,
  <Route key="crime-gangs" path="/crime/gangs" element={<GenericSubcategoryPage />} />,
  <Route key="crime-gangsters" path="/crime/gangsters" element={<GenericSubcategoryPage />} />,
  <Route key="police" path="/police" element={<GenericSubcategoryPage />} />,
  <Route key="police-chases" path="/police/chases" element={<GenericSubcategoryPage />} />,
  <Route key="police-stops" path="/police/stops" element={<GenericSubcategoryPage />} />,
  <Route key="police-sheriff" path="/police/sheriff" element={<GenericSubcategoryPage />} />,
  <Route key="jails" path="/jails" element={<GenericSubcategoryPage />} />,
  <Route key="jails-prisons" path="/jails/prisons" element={<GenericSubcategoryPage />} />,
  <Route key="jails-county" path="/jails/county" element={<GenericSubcategoryPage />} />,
  <Route key="attorneys" path="/attorneys" element={<GenericSubcategoryPage />} />,
  <Route key="attorneys-info" path="/attorneys/info" element={<GenericSubcategoryPage />} />,
  <Route key="attorneys-cases" path="/attorneys/cases" element={<GenericSubcategoryPage />} />,

  // Business & Finance routes
  <Route key="business" path="/business" element={<GenericSubcategoryPage />} />,
  <Route key="business-crypto" path="/business/crypto" element={<GenericSubcategoryPage />} />,
  <Route key="business-developments" path="/business/developments" element={<GenericSubcategoryPage />} />,
  <Route key="business-leaders" path="/business/leaders" element={<GenericSubcategoryPage />} />,
  <Route key="business-money" path="/business/money" element={<GenericSubcategoryPage />} />,
  <Route key="business-services" path="/business/services" element={<GenericSubcategoryPage />} />,
  <Route key="business-farming" path="/business/farming" element={<GenericSubcategoryPage />} />,
  <Route key="stocks" path="/stocks" element={<GenericSubcategoryPage />} />,
  <Route key="stocks-commodity" path="/stocks/commodity" element={<GenericSubcategoryPage />} />,
  <Route key="stocks-cash" path="/stocks/cash" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate" path="/real-estate" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate-residential" path="/real-estate/residential" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate-commercial" path="/real-estate/commercial" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate-luxury" path="/real-estate/luxury" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate-land" path="/real-estate/land" element={<GenericSubcategoryPage />} />,
  <Route key="advertising" path="/advertising" element={<GenericSubcategoryPage />} />,
  <Route key="advertising-tips" path="/advertising/tips" element={<GenericSubcategoryPage />} />,
  <Route key="advertising-campaigns" path="/advertising/campaigns" element={<GenericSubcategoryPage />} />,
  <Route key="food-products" path="/food-products" element={<GenericSubcategoryPage />} />,
  <Route key="food-products-business" path="/food-products/business" element={<GenericSubcategoryPage />} />,

  // Food & Drinks routes
  <Route key="foods" path="/foods" element={<GenericSubcategoryPage />} />,
  <Route key="foods-bluefin" path="/foods/bluefin" element={<GenericSubcategoryPage />} />,
  <Route key="foods-cooking" path="/foods/cooking" element={<GenericSubcategoryPage />} />,
  <Route key="foods-seafood" path="/foods/seafood" element={<GenericSubcategoryPage />} />,
  <Route key="foods-dieting" path="/foods/dieting" element={<GenericSubcategoryPage />} />,
  <Route key="foods-fruits" path="/foods/fruits" element={<GenericSubcategoryPage />} />,
  <Route key="foods-gain-weight" path="/foods/gain-weight" element={<GenericSubcategoryPage />} />,
  <Route key="foods-sweets" path="/foods/sweets" element={<GenericSubcategoryPage />} />,
  <Route key="foods-harvest" path="/foods/harvest" element={<GenericSubcategoryPage />} />,
  <Route key="foods-healthy" path="/foods/healthy" element={<GenericSubcategoryPage />} />,
  <Route key="drinks" path="/drinks" element={<GenericSubcategoryPage />} />,
  <Route key="drinks-alcohol" path="/drinks/alcohol" element={<GenericSubcategoryPage />} />,
  <Route key="drinks-non-alcohol" path="/drinks/non-alcohol" element={<GenericSubcategoryPage />} />,
  <Route key="restaurants" path="/restaurants" element={<GenericSubcategoryPage />} />,
  <Route key="restaurants-fine-dining" path="/restaurants/fine-dining" element={<GenericSubcategoryPage />} />,
  <Route key="restaurants-fast-food" path="/restaurants/fast-food" element={<GenericSubcategoryPage />} />,

  // Environment & Weather routes
  <Route key="weather" path="/weather" element={<GenericSubcategoryPage />} />,
  <Route key="weather-storms" path="/weather/storms" element={<GenericSubcategoryPage />} />,
  <Route key="weather-lightning" path="/weather/lightning" element={<GenericSubcategoryPage />} />,
  <Route key="disasters" path="/disasters" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-avalanche" path="/disasters/avalanche" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-blizzard" path="/disasters/blizzard" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-earthquakes" path="/disasters/earthquakes" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-fires" path="/disasters/fires" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-hurricanes" path="/disasters/hurricanes" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-volcano" path="/disasters/volcano" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-floods" path="/disasters/floods" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-landslide" path="/disasters/landslide" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-tornado" path="/disasters/tornado" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-tsunami" path="/disasters/tsunami" element={<GenericSubcategoryPage />} />,

  // Entertainment & Media routes
  <Route key="entertainment" path="/entertainment" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-oscars" path="/entertainment/oscars" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-actors" path="/entertainment/actors" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-late-night" path="/entertainment/late-night" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-podcasts" path="/entertainment/podcasts" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-auditions" path="/entertainment/auditions" element={<GenericSubcategoryPage />} />,
  <Route key="film" path="/film" element={<GenericSubcategoryPage />} />,
  <Route key="film-romance" path="/film/romance" element={<GenericSubcategoryPage />} />,
  <Route key="film-action" path="/film/action" element={<GenericSubcategoryPage />} />,
  <Route key="film-thriller" path="/film/thriller" element={<GenericSubcategoryPage />} />,
  <Route key="film-adventure" path="/film/adventure" element={<GenericSubcategoryPage />} />,
  <Route key="film-comedy" path="/film/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="film-drama" path="/film/drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-documentary" path="/film/documentary" element={<GenericSubcategoryPage />} />,
  <Route key="film-gangsters" path="/film/gangsters" element={<GenericSubcategoryPage />} />,
  <Route key="film-mystery" path="/film/mystery" element={<GenericSubcategoryPage />} />,
  <Route key="film-war" path="/film/war" element={<GenericSubcategoryPage />} />,
  <Route key="film-westerns" path="/film/westerns" element={<GenericSubcategoryPage />} />,
  <Route key="film-scientific" path="/film/scientific" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation" path="/film-animation" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-action" path="/film-animation/action" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-fantasy" path="/film-animation/fantasy" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-adventure" path="/film-animation/adventure" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-cartoons" path="/film-animation/cartoons" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-comedy" path="/film-animation/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-drama" path="/film-animation/drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-musical" path="/film-animation/musical" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-parody" path="/film-animation/parody" element={<GenericSubcategoryPage />} />,
  <Route key="film-animation-short" path="/film-animation/short" element={<GenericSubcategoryPage />} />,
  <Route key="tv-shows" path="/tv-shows" element={<GenericSubcategoryPage />} />,
  <Route key="tv-shows-news" path="/tv-shows/news" element={<GenericSubcategoryPage />} />,
  <Route key="tv-shows-talk" path="/tv-shows/talk" element={<GenericSubcategoryPage />} />,
  <Route key="tv-shows-court" path="/tv-shows/court" element={<GenericSubcategoryPage />} />,
  <Route key="hollywood" path="/hollywood" element={<GenericSubcategoryPage />} />,
  <Route key="hollywood-celebrities" path="/hollywood/celebrities" element={<GenericSubcategoryPage />} />,
  <Route key="hollywood-journalists" path="/hollywood/journalists" element={<GenericSubcategoryPage />} />,

  // Comedy & Funny routes
  <Route key="comedy" path="/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-standup" path="/comedy/standup" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-roasts" path="/comedy/roasts" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-snl" path="/comedy/snl" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-sitcom" path="/comedy/sitcom" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-comedians" path="/comedy/comedians" element={<GenericSubcategoryPage />} />,
  <Route key="pranks" path="/pranks" element={<GenericSubcategoryPage />} />,
  <Route key="pranks-work" path="/pranks/work" element={<GenericSubcategoryPage />} />,
  <Route key="pranks-home" path="/pranks/home" element={<GenericSubcategoryPage />} />,
  <Route key="pranks-weird" path="/pranks/weird" element={<GenericSubcategoryPage />} />,
  <Route key="funny" path="/funny" element={<GenericSubcategoryPage />} />,
  <Route key="funny-shorts" path="/funny/shorts" element={<GenericSubcategoryPage />} />,
  <Route key="funny-weird" path="/funny/weird" element={<GenericSubcategoryPage />} />,
  <Route key="funny-videos" path="/funny/videos" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers" path="/bloopers" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers-movies" path="/bloopers/movies" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers-tv" path="/bloopers/tv" element={<GenericSubcategoryPage />} />,
  <Route key="fails" path="/fails" element={<GenericSubcategoryPage />} />,
  <Route key="fails-expensive" path="/fails/expensive" element={<GenericSubcategoryPage />} />,
  <Route key="fails-people" path="/fails/people" element={<GenericSubcategoryPage />} />,
  
  // Crazy & Amazing routes
  <Route key="crazy" path="/crazy" element={<GenericSubcategoryPage />} />,
  <Route key="crazy-amazing" path="/crazy/amazing" element={<GenericSubcategoryPage />} />,
  <Route key="crazy-wouldnt-believe" path="/crazy/wouldnt-believe" element={<GenericSubcategoryPage />} />,
  
  // Comedians routes
  <Route key="comedians" path="/comedians" element={<GenericSubcategoryPage />} />,
  <Route key="comedians-interviews" path="/comedians/interviews" element={<GenericSubcategoryPage />} />,
  <Route key="comedians-specials" path="/comedians/specials" element={<GenericSubcategoryPage />} />,
  
  // Additional comedy routes
  <Route key="comedy-pranks" path="/comedy/pranks" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-jokes" path="/comedy/jokes" element={<GenericSubcategoryPage />} />,
  <Route key="funny-pranks" path="/funny/pranks" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers-screwup" path="/bloopers/screwup" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers-fails" path="/bloopers/fails" element={<GenericSubcategoryPage />} />,

  // Music routes
  <Route key="music" path="/music" element={<GenericSubcategoryPage />} />,
  <Route key="music-rock" path="/music/rock" element={<GenericSubcategoryPage />} />,
  <Route key="music-pop" path="/music/pop" element={<GenericSubcategoryPage />} />,
  <Route key="music-hip-hop" path="/music/hip-hop" element={<GenericSubcategoryPage />} />,
  <Route key="music-rap" path="/music/rap" element={<GenericSubcategoryPage />} />,
  <Route key="music-r-and-b" path="/music/r-and-b" element={<GenericSubcategoryPage />} />,
  <Route key="music-soul" path="/music/soul" element={<GenericSubcategoryPage />} />,
  <Route key="music-country" path="/music/country" element={<GenericSubcategoryPage />} />,
  <Route key="music-blues" path="/music/blues" element={<GenericSubcategoryPage />} />,
  <Route key="music-jazz" path="/music/jazz" element={<GenericSubcategoryPage />} />,
  <Route key="music-classical" path="/music/classical" element={<GenericSubcategoryPage />} />,
  <Route key="music-folk" path="/music/folk" element={<GenericSubcategoryPage />} />,
  <Route key="music-funk" path="/music/funk" element={<GenericSubcategoryPage />} />,
  <Route key="music-metal" path="/music/metal" element={<GenericSubcategoryPage />} />,
  <Route key="music-alternative" path="/music/alternative" element={<GenericSubcategoryPage />} />,
  <Route key="music-spanish" path="/music/spanish" element={<GenericSubcategoryPage />} />,
  <Route key="music-chinese" path="/music/chinese" element={<GenericSubcategoryPage />} />,
  <Route key="music-mariachi" path="/music/mariachi" element={<GenericSubcategoryPage />} />,
  <Route key="music-salsa" path="/music/salsa" element={<GenericSubcategoryPage />} />,
  <Route key="music-reggaeton" path="/music/reggaeton" element={<GenericSubcategoryPage />} />,
  <Route key="music-christian" path="/music/christian" element={<GenericSubcategoryPage />} />,
  <Route key="music-christmas" path="/music/christmas" element={<GenericSubcategoryPage />} />,
  <Route key="music-soundtracks" path="/music/soundtracks" element={<GenericSubcategoryPage />} />,
  <Route key="music-parody" path="/music/parody" element={<GenericSubcategoryPage />} />,
  <Route key="music-relaxation" path="/music/relaxation" element={<GenericSubcategoryPage />} />,
  <Route key="music-soul-train" path="/music/soul-train" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists" path="/music-artists" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists-interviews" path="/music-artists/interviews" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists-news" path="/music-artists/news" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists-works" path="/music-artists/works" element={<GenericSubcategoryPage />} />,
  <Route key="music-instruments" path="/music-instruments" element={<GenericSubcategoryPage />} />,
  <Route key="music-instruments-guitar" path="/music-instruments/guitar" element={<GenericSubcategoryPage />} />,
  <Route key="music-instruments-piano" path="/music-instruments/piano" element={<GenericSubcategoryPage />} />,
  <Route key="dances" path="/dances" element={<GenericSubcategoryPage />} />,
  <Route key="dances-styles" path="/dances/styles" element={<GenericSubcategoryPage />} />,
  <Route key="dances-choreography" path="/dances/choreography" element={<GenericSubcategoryPage />} />,

  // Gaming & Hobbies routes
  <Route key="gaming" path="/gaming" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-arcade" path="/gaming/arcade" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-casino" path="/gaming/casino" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-dominos" path="/gaming/dominos" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-lottery" path="/gaming/lottery" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-console" path="/gaming/console" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-cards" path="/gaming/cards" element={<GenericSubcategoryPage />} />,
  <Route key="gaming-challenges" path="/gaming/challenges" element={<GenericSubcategoryPage />} />,
  <Route key="magic-tricks" path="/magic-tricks" element={<GenericSubcategoryPage />} />,
  <Route key="magic-tricks-illusions" path="/magic-tricks/illusions" element={<GenericSubcategoryPage />} />,
  <Route key="magic-tricks-street" path="/magic-tricks/street" element={<GenericSubcategoryPage />} />,
  <Route key="toys" path="/toys" element={<GenericSubcategoryPage />} />,
  <Route key="toys-rockets" path="/toys/rockets" element={<GenericSubcategoryPage />} />,
  <Route key="toys-rc" path="/toys/rc" element={<GenericSubcategoryPage />} />,
  <Route key="riddles" path="/riddles" element={<GenericSubcategoryPage />} />,
  <Route key="riddles-puzzles" path="/riddles/puzzles" element={<GenericSubcategoryPage />} />,

  // Fitness & Health routes
  <Route key="physical-fitness" path="/physical-fitness" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-calisthenics" path="/physical-fitness/calisthenics" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-weight-lifting" path="/physical-fitness/weight-lifting" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-weightlifting-female" path="/physical-fitness/weightlifting-female" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-weightlifting-male" path="/physical-fitness/weightlifting-male" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-workout" path="/physical-fitness/workout" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-workout-female" path="/physical-fitness/workout-female" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-workout-male" path="/physical-fitness/workout-male" element={<GenericSubcategoryPage />} />,
  <Route key="physical-fitness-yoga" path="/physical-fitness/yoga" element={<GenericSubcategoryPage />} />,
  <Route key="martial-arts" path="/martial-arts" element={<GenericSubcategoryPage />} />,
  <Route key="martial-arts-self-defense" path="/martial-arts/self-defense" element={<GenericSubcategoryPage />} />,
  <Route key="martial-arts-mma" path="/martial-arts/mma" element={<GenericSubcategoryPage />} />,
  <Route key="swimming" path="/swimming" element={<GenericSubcategoryPage />} />,
  <Route key="swimming-diving" path="/swimming/diving" element={<GenericSubcategoryPage />} />,
  <Route key="swimming-laps" path="/swimming/laps" element={<GenericSubcategoryPage />} />,
  <Route key="hair-beauty" path="/hair-beauty" element={<GenericSubcategoryPage />} />,
  <Route key="hair-beauty-cuts" path="/hair-beauty/cuts" element={<GenericSubcategoryPage />} />,
  <Route key="hair-beauty-styles" path="/hair-beauty/styles" element={<GenericSubcategoryPage />} />,
  <Route key="hair-beauty-extensions" path="/hair-beauty/extensions" element={<GenericSubcategoryPage />} />,
  <Route key="cosmetics" path="/cosmetics" element={<GenericSubcategoryPage />} />,
  <Route key="cosmetics-eyelashes" path="/cosmetics/eyelashes" element={<GenericSubcategoryPage />} />,
  <Route key="cosmetics-foundation" path="/cosmetics/foundation" element={<GenericSubcategoryPage />} />,
  <Route key="cosmetics-lipstick" path="/cosmetics/lipstick" element={<GenericSubcategoryPage />} />,

  // Models & Photos routes
  <Route key="models" path="/models" element={<GenericSubcategoryPage />} />,
  <Route key="models-fashion" path="/models/fashion" element={<GenericSubcategoryPage />} />,
  <Route key="models-female-male" path="/models/female-male" element={<GenericSubcategoryPage />} />,
  <Route key="models-fit" path="/models/fit" element={<GenericSubcategoryPage />} />,
  <Route key="models-mature" path="/models/mature" element={<GenericSubcategoryPage />} />,
  <Route key="models-plus-size" path="/models/plus-size" element={<GenericSubcategoryPage />} />,
  <Route key="models-seasonal" path="/models/seasonal" element={<GenericSubcategoryPage />} />,
  <Route key="models-swimsuit" path="/models/swimsuit" element={<GenericSubcategoryPage />} />,
  <Route key="models-winter" path="/models/winter" element={<GenericSubcategoryPage />} />,
  <Route key="models-summer" path="/models/summer" element={<GenericSubcategoryPage />} />,
  <Route key="models-fall" path="/models/fall" element={<GenericSubcategoryPage />} />,
  <Route key="pictures" path="/pictures" element={<GenericSubcategoryPage />} />,
  <Route key="pictures-photos" path="/pictures/photos" element={<GenericSubcategoryPage />} />,
  <Route key="pictures-art" path="/pictures/art" element={<GenericSubcategoryPage />} />,

  // Travel & Places routes
  <Route key="travel" path="/travel" element={<GenericSubcategoryPage />} />,
  <Route key="travel-beaches" path="/travel/beaches" element={<GenericSubcategoryPage />} />,
  <Route key="travel-cities" path="/travel/cities" element={<GenericSubcategoryPage />} />,
  <Route key="travel-foods" path="/travel/foods" element={<GenericSubcategoryPage />} />,
  <Route key="travel-hotels" path="/travel/hotels" element={<GenericSubcategoryPage />} />,
  <Route key="travel-luxury-hotels" path="/travel/luxury-hotels" element={<GenericSubcategoryPage />} />,
  <Route key="travel-unique-hotels" path="/travel/unique-hotels" element={<GenericSubcategoryPage />} />,
  <Route key="travel-nightclubs" path="/travel/nightclubs" element={<GenericSubcategoryPage />} />,
  <Route key="travel-restaurants" path="/travel/restaurants" element={<GenericSubcategoryPage />} />,
  <Route key="travel-street-food" path="/travel/street-food" element={<GenericSubcategoryPage />} />,
  <Route key="travel-streets" path="/travel/streets" element={<GenericSubcategoryPage />} />,
  <Route key="travel-new-year" path="/travel/new-year" element={<GenericSubcategoryPage />} />,
  <Route key="travel-tips" path="/travel/tips" element={<GenericSubcategoryPage />} />,

  // How-To & Education routes
  <Route key="howto" path="/howto" element={<GenericSubcategoryPage />} />,
  <Route key="howto-building" path="/howto/building" element={<GenericSubcategoryPage />} />,
  <Route key="howto-cleaning" path="/howto/cleaning" element={<GenericSubcategoryPage />} />,
  <Route key="howto-bathroom" path="/howto/bathroom" element={<GenericSubcategoryPage />} />,
  <Route key="howto-windows" path="/howto/windows" element={<GenericSubcategoryPage />} />,
  <Route key="howto-toilets" path="/howto/toilets" element={<GenericSubcategoryPage />} />,
  <Route key="howto-electrical" path="/howto/electrical" element={<GenericSubcategoryPage />} />,
  <Route key="howto-arts-crafts" path="/howto/arts-crafts" element={<GenericSubcategoryPage />} />,
  <Route key="education" path="/education" element={<GenericSubcategoryPage />} />,
  <Route key="education-anatomy" path="/education/anatomy" element={<GenericSubcategoryPage />} />,
  <Route key="education-countries" path="/education/countries" element={<GenericSubcategoryPage />} />,
  <Route key="education-immigration" path="/education/immigration" element={<GenericSubcategoryPage />} />,
  <Route key="education-geography" path="/education/geography" element={<GenericSubcategoryPage />} />,
  <Route key="education-laws" path="/education/laws" element={<GenericSubcategoryPage />} />,
  <Route key="education-medicine" path="/education/medicine" element={<GenericSubcategoryPage />} />,
  <Route key="education-religion" path="/education/religion" element={<GenericSubcategoryPage />} />,
  <Route key="education-nursing" path="/education/nursing" element={<GenericSubcategoryPage />} />,
  <Route key="education-learning" path="/education/learning" element={<GenericSubcategoryPage />} />,
  <Route key="kids" path="/kids" element={<GenericSubcategoryPage />} />,
  <Route key="kids-beauty" path="/kids/beauty" element={<GenericSubcategoryPage />} />,
  <Route key="kids-cartoons" path="/kids/cartoons" element={<GenericSubcategoryPage />} />,
  <Route key="kids-education" path="/kids/education" element={<GenericSubcategoryPage />} />,
  <Route key="kids-funny" path="/kids/funny" element={<GenericSubcategoryPage />} />,
  <Route key="kids-oceanography" path="/kids/oceanography" element={<GenericSubcategoryPage />} />,
  <Route key="kids-animals" path="/kids/animals" element={<GenericSubcategoryPage />} />,
  <Route key="kids-animation" path="/kids/animation" element={<GenericSubcategoryPage />} />,
  <Route key="kids-alphabets" path="/kids/alphabets" element={<GenericSubcategoryPage />} />,
  <Route key="kids-colors" path="/kids/colors" element={<GenericSubcategoryPage />} />,
  <Route key="kids-foods" path="/kids/foods" element={<GenericSubcategoryPage />} />,
  <Route key="kids-math" path="/kids/math" element={<GenericSubcategoryPage />} />,
  <Route key="kids-reading" path="/kids/reading" element={<GenericSubcategoryPage />} />,
  <Route key="kids-films" path="/kids/films" element={<GenericSubcategoryPage />} />,
  <Route key="kids-games" path="/kids/games" element={<GenericSubcategoryPage />} />,
  <Route key="kids-music" path="/kids/music" element={<GenericSubcategoryPage />} />,
  <Route key="kids-videos" path="/kids/videos" element={<GenericSubcategoryPage />} />,

  // People & Workers routes
  <Route key="people" path="/people" element={<GenericSubcategoryPage />} />,
  <Route key="people-bigotry" path="/people/bigotry" element={<GenericSubcategoryPage />} />,
  <Route key="people-fighting" path="/people/fighting" element={<GenericSubcategoryPage />} />,
  <Route key="people-karma" path="/people/karma" element={<GenericSubcategoryPage />} />,
  <Route key="people-lookalikes" path="/people/lookalikes" element={<GenericSubcategoryPage />} />,
  <Route key="people-thefts" path="/people/thefts" element={<GenericSubcategoryPage />} />,
  <Route key="people-amazing" path="/people/amazing" element={<GenericSubcategoryPage />} />,
  <Route key="people-fails" path="/people/fails" element={<GenericSubcategoryPage />} />,
  <Route key="workers" path="/workers" element={<GenericSubcategoryPage />} />,
  <Route key="workers-fails" path="/workers/fails" element={<GenericSubcategoryPage />} />,
  <Route key="workers-amazing" path="/workers/amazing" element={<GenericSubcategoryPage />} />,
  <Route key="babies" path="/babies" element={<GenericSubcategoryPage />} />,
  <Route key="babies-funny" path="/babies/funny" element={<GenericSubcategoryPage />} />,
  <Route key="babies-cute" path="/babies/cute" element={<GenericSubcategoryPage />} />,
  <Route key="speeches" path="/speeches" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-commencement" path="/speeches/commencement" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-eulogy" path="/speeches/eulogy" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-informative" path="/speeches/informative" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-motivational" path="/speeches/motivational" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-persuasive" path="/speeches/persuasive" element={<GenericSubcategoryPage />} />,
  <Route key="motivation" path="/motivation" element={<GenericSubcategoryPage />} />,
  <Route key="motivation-self" path="/motivation/self" element={<GenericSubcategoryPage />} />,
  <Route key="success" path="/success" element={<GenericSubcategoryPage />} />,
  <Route key="success-stories" path="/success/stories" element={<GenericSubcategoryPage />} />,

  // Sports Extended routes
  <Route key="sports" path="/sports" element={<GenericSubcategoryPage />} />,
  <Route key="sports-arenas" path="/sports/arenas" element={<GenericSubcategoryPage />} />,
  <Route key="sports-basketball" path="/sports/basketball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-car-racing" path="/sports/car-racing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-comedy" path="/sports/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="sports-fishing" path="/sports/fishing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-interviews" path="/sports/interviews" element={<GenericSubcategoryPage />} />,
  <Route key="sports-kickboxing" path="/sports/kickboxing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mlb" path="/sports/mlb" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nba" path="/sports/nba" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nfl" path="/sports/nfl" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl" path="/sports/nhl" element={<GenericSubcategoryPage />} />,
  <Route key="sports-pga" path="/sports/pga" element={<GenericSubcategoryPage />} />,
  <Route key="sports-race-car" path="/sports/race-car" element={<GenericSubcategoryPage />} />,
  <Route key="sports-cycling" path="/sports/cycling" element={<GenericSubcategoryPage />} />,
  <Route key="sports-rugby" path="/sports/rugby" element={<GenericSubcategoryPage />} />,
  <Route key="sports-soccer" path="/sports/soccer" element={<GenericSubcategoryPage />} />,
  <Route key="sports-surfing" path="/sports/surfing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-tennis-men" path="/sports/tennis-men" element={<GenericSubcategoryPage />} />,
  <Route key="sports-tennis-women" path="/sports/tennis-women" element={<GenericSubcategoryPage />} />,
  <Route key="sports-track-field" path="/sports/track-field" element={<GenericSubcategoryPage />} />,
  <Route key="sports-volleyball" path="/sports/volleyball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-weightlifting" path="/sports/weightlifting" element={<GenericSubcategoryPage />} />,
  <Route key="sports-wwe" path="/sports/wwe" element={<GenericSubcategoryPage />} />,
  <Route key="sports-boxing" path="/sports/boxing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-boxing-interviews" path="/sports/boxing-interviews" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college" path="/sports/college" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-baseball" path="/sports/college-baseball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-basketball" path="/sports/college-basketball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-football" path="/sports/college-football" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-track" path="/sports/college-track" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-women-basketball" path="/sports/college-women-basketball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-fan-challenges" path="/sports/fan-challenges" element={<GenericSubcategoryPage />} />,
  <Route key="sports-high-school" path="/sports/high-school" element={<GenericSubcategoryPage />} />,
  <Route key="sports-formula-one" path="/sports/formula-one" element={<GenericSubcategoryPage />} />,
  <Route key="sports-golf-ryder" path="/sports/golf-ryder" element={<GenericSubcategoryPage />} />,
  <Route key="sports-country-hockey" path="/sports/country-hockey" element={<GenericSubcategoryPage />} />,
  <Route key="sports-horse-racing" path="/sports/horse-racing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-equestrian" path="/sports/equestrian" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mlb-playoffs" path="/sports/mlb-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-world-series" path="/sports/world-series" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mls" path="/sports/mls" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mma" path="/sports/mma" element={<GenericSubcategoryPage />} />,
  <Route key="sports-superbike" path="/sports/superbike" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nascar" path="/sports/nascar" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nba-playoffs" path="/sports/nba-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nfl-superbowl" path="/sports/nfl-superbowl" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl-playoffs" path="/sports/nhl-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl-allstar" path="/sports/nhl-allstar" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhra" path="/sports/nhra" element={<GenericSubcategoryPage />} />,
  <Route key="sports-olympics" path="/sports/olympics" element={<GenericSubcategoryPage />} />,
  <Route key="sports-personalities" path="/sports/personalities" element={<GenericSubcategoryPage />} />,
  <Route key="sports-pro-golf" path="/sports/pro-golf" element={<GenericSubcategoryPage />} />,
  <Route key="sports-beach-volleyball" path="/sports/beach-volleyball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-pro-volleyball" path="/sports/pro-volleyball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-wnba" path="/sports/wnba" element={<GenericSubcategoryPage />} />,
  <Route key="sports-wnba-playoffs" path="/sports/wnba-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-women-mma" path="/sports/women-mma" element={<GenericSubcategoryPage />} />,
  <Route key="sports-news" path="/sports/news" element={<GenericSubcategoryPage />} />,

  // History & Artifacts routes
  <Route key="history" path="/history" element={<GenericSubcategoryPage />} />,
  <Route key="history-american" path="/history/american" element={<GenericSubcategoryPage />} />,
  <Route key="history-biblical" path="/history/biblical" element={<GenericSubcategoryPage />} />,
  <Route key="history-world" path="/history/world" element={<GenericSubcategoryPage />} />,
  <Route key="artifacts" path="/artifacts" element={<GenericSubcategoryPage />} />,
  <Route key="artifacts-antiques" path="/artifacts/antiques" element={<GenericSubcategoryPage />} />,
  <Route key="artifacts-colosseum" path="/artifacts/colosseum" element={<GenericSubcategoryPage />} />,
  <Route key="statues" path="/statues" element={<GenericSubcategoryPage />} />,
  <Route key="statues-sculptures" path="/statues/sculptures" element={<GenericSubcategoryPage />} />,
  <Route key="statues-carvers" path="/statues/carvers" element={<GenericSubcategoryPage />} />,
  <Route key="bible" path="/bible" element={<GenericSubcategoryPage />} />,
  <Route key="bible-quotes" path="/bible/quotes" element={<GenericSubcategoryPage />} />,
  <Route key="bible-scriptures" path="/bible/scriptures" element={<GenericSubcategoryPage />} />,

  // Government & Politics routes
  <Route key="government" path="/government" element={<GenericSubcategoryPage />} />,
  <Route key="government-senate" path="/government/senate" element={<GenericSubcategoryPage />} />,
  <Route key="government-house" path="/government/house" element={<GenericSubcategoryPage />} />,
  <Route key="presidents" path="/presidents" element={<GenericSubcategoryPage />} />,
  <Route key="presidents-motorcade" path="/presidents/motorcade" element={<GenericSubcategoryPage />} />,
  <Route key="presidents-airforce" path="/presidents/airforce" element={<GenericSubcategoryPage />} />,
  <Route key="presidents-former" path="/presidents/former" element={<GenericSubcategoryPage />} />,
  <Route key="politics" path="/politics" element={<GenericSubcategoryPage />} />,
  <Route key="politics-news" path="/politics/news" element={<GenericSubcategoryPage />} />,
  <Route key="politics-podcasts" path="/politics/podcasts" element={<GenericSubcategoryPage />} />,
  <Route key="protesters" path="/protesters" element={<GenericSubcategoryPage />} />,
  <Route key="protesters-demonstrations" path="/protesters/demonstrations" element={<GenericSubcategoryPage />} />,
  <Route key="military" path="/military" element={<GenericSubcategoryPage />} />,
  <Route key="military-pilots" path="/military/pilots" element={<GenericSubcategoryPage />} />,
  <Route key="military-reserves" path="/military/reserves" element={<GenericSubcategoryPage />} />,
  <Route key="military-weapons" path="/military/weapons" element={<GenericSubcategoryPage />} />,
  <Route key="military-aircrafts" path="/military/aircrafts" element={<GenericSubcategoryPage />} />,
  <Route key="military-documentary" path="/military/documentary" element={<GenericSubcategoryPage />} />,
  <Route key="military-ships" path="/military/ships" element={<GenericSubcategoryPage />} />,
  <Route key="military-submarines" path="/military/submarines" element={<GenericSubcategoryPage />} />,
  <Route key="military-war" path="/military/war" element={<GenericSubcategoryPage />} />,
  <Route key="military-drones" path="/military/drones" element={<GenericSubcategoryPage />} />,
  <Route key="military-personnel" path="/military/personnel" element={<GenericSubcategoryPage />} />,
  <Route key="weapons" path="/weapons" element={<GenericSubcategoryPage />} />,
  <Route key="weapons-civilian" path="/weapons/civilian" element={<GenericSubcategoryPage />} />,

  // Lifestyle routes
  <Route key="relationships" path="/relationships" element={<GenericSubcategoryPage />} />,
  <Route key="relationships-divorce" path="/relationships/divorce" element={<GenericSubcategoryPage />} />,
  <Route key="relationships-love" path="/relationships/love" element={<GenericSubcategoryPage />} />,
  <Route key="relationships-marriage" path="/relationships/marriage" element={<GenericSubcategoryPage />} />,
  <Route key="dating" path="/dating" element={<GenericSubcategoryPage />} />,
  <Route key="dating-flirting" path="/dating/flirting" element={<GenericSubcategoryPage />} />,
  <Route key="dating-breakups" path="/dating/breakups" element={<GenericSubcategoryPage />} />,
  <Route key="dating-tips" path="/dating/tips" element={<GenericSubcategoryPage />} />,
  <Route key="dating-single" path="/dating/single" element={<GenericSubcategoryPage />} />,
  <Route key="dating-attraction" path="/dating/attraction" element={<GenericSubcategoryPage />} />,
  <Route key="intimacy" path="/intimacy" element={<GenericSubcategoryPage />} />,
  <Route key="intimacy-relationships" path="/intimacy/relationships" element={<GenericSubcategoryPage />} />,
  <Route key="ideology" path="/ideology" element={<GenericSubcategoryPage />} />,
  <Route key="ideology-lifestyles" path="/ideology/lifestyles" element={<GenericSubcategoryPage />} />,

  // Documentaries & Drugs routes
  <Route key="documentaries" path="/documentaries" element={<GenericSubcategoryPage />} />,
  <Route key="documentaries-drugs" path="/documentaries/drugs" element={<GenericSubcategoryPage />} />,
  <Route key="documentaries-real-events" path="/documentaries/real-events" element={<GenericSubcategoryPage />} />,
  <Route key="drugs" path="/drugs" element={<GenericSubcategoryPage />} />,
  <Route key="drugs-dealers" path="/drugs/dealers" element={<GenericSubcategoryPage />} />,
  <Route key="drugs-addiction" path="/drugs/addiction" element={<GenericSubcategoryPage />} />,

  // Quotes & Poems routes
  <Route key="quotes" path="/quotes" element={<GenericSubcategoryPage />} />,
  <Route key="quotes-poems" path="/quotes/poems" element={<GenericSubcategoryPage />} />,
  <Route key="quotes-statements" path="/quotes/statements" element={<GenericSubcategoryPage />} />,

  // Radio routes
  <Route key="radio" path="/radio" element={<GenericSubcategoryPage />} />,
  <Route key="radio-music" path="/radio/music" element={<GenericSubcategoryPage />} />,
  <Route key="radio-podcast" path="/radio/podcast" element={<GenericSubcategoryPage />} />,
  <Route key="radio-rc" path="/radio/rc" element={<GenericSubcategoryPage />} />,
  <Route key="radio-shows" path="/radio/shows" element={<GenericSubcategoryPage />} />,

  // Moments routes
  <Route key="moments" path="/moments" element={<GenericSubcategoryPage />} />,
  <Route key="moments-special" path="/moments/special" element={<GenericSubcategoryPage />} />,
  <Route key="moments-good-bad" path="/moments/good-bad" element={<GenericSubcategoryPage />} />,

  // Drones routes
  <Route key="drones" path="/drones" element={<GenericSubcategoryPage />} />,
  <Route key="drones-civilian" path="/drones/civilian" element={<GenericSubcategoryPage />} />,
  <Route key="drones-recreational" path="/drones/recreational" element={<GenericSubcategoryPage />} />,

  // Animation routes (separate from film-animation)
  <Route key="animation" path="/animation" element={<GenericSubcategoryPage />} />,
  <Route key="animation-action" path="/animation/action" element={<GenericSubcategoryPage />} />,
  <Route key="animation-fantasy" path="/animation/fantasy" element={<GenericSubcategoryPage />} />,
  <Route key="animation-adventure" path="/animation/adventure" element={<GenericSubcategoryPage />} />,
  <Route key="animation-cartoons" path="/animation/cartoons" element={<GenericSubcategoryPage />} />,
  <Route key="animation-comedy" path="/animation/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="animation-drama" path="/animation/drama" element={<GenericSubcategoryPage />} />,
  <Route key="animation-musical" path="/animation/musical" element={<GenericSubcategoryPage />} />,
  <Route key="animation-parody" path="/animation/parody" element={<GenericSubcategoryPage />} />,
  <Route key="animation-short" path="/animation/short" element={<GenericSubcategoryPage />} />,

  // Additional Film routes
  <Route key="film-action-crime" path="/film/action-crime" element={<GenericSubcategoryPage />} />,
  <Route key="film-comedy-drama" path="/film/comedy-drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-crime-drama" path="/film/crime-drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-clips" path="/film/clips" element={<GenericSubcategoryPage />} />,

  // Additional Entertainment routes
  <Route key="entertainment-podcast" path="/entertainment/podcast" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-hollywood" path="/entertainment/hollywood" element={<GenericSubcategoryPage />} />,

  // Flat routes for SidebarSearch compatibility
  // Aviation flat routes
  <Route key="airplanes-airships-flat" path="/airplanes-airships" element={<GenericSubcategoryPage />} />,
  <Route key="cargo-planes" path="/cargo-planes" element={<GenericSubcategoryPage />} />,
  <Route key="commercial-jumbo-jets" path="/commercial-jumbo-jets" element={<GenericSubcategoryPage />} />,
  <Route key="land-water-planes" path="/land-water-planes" element={<GenericSubcategoryPage />} />,
  <Route key="pilots-captains" path="/pilots-captains" element={<GenericSubcategoryPage />} />,
  <Route key="single-engine-planes" path="/single-engine-planes" element={<GenericSubcategoryPage />} />,
  <Route key="aircraft-fleet" path="/aircraft-fleet" element={<GenericSubcategoryPage />} />,
  <Route key="airport-improvements" path="/airport-improvements" element={<GenericSubcategoryPage />} />,
  <Route key="airport-fails" path="/airport-fails" element={<GenericSubcategoryPage />} />,
  <Route key="helicopters-commercial-flat" path="/helicopters-commercial" element={<GenericSubcategoryPage />} />,
  <Route key="helicopters-private-flat" path="/helicopters-private" element={<GenericSubcategoryPage />} />,
  
  // Animals flat routes
  <Route key="amphibians" path="/amphibians" element={<GenericSubcategoryPage />} />,
  <Route key="insects-spiders" path="/insects-spiders" element={<GenericSubcategoryPage />} />,
  <Route key="birds-raptors" path="/birds-raptors" element={<GenericSubcategoryPage />} />,
  <Route key="crabs-lobsters" path="/crabs-lobsters" element={<GenericSubcategoryPage />} />,
  <Route key="fish" path="/fish" element={<GenericSubcategoryPage />} />,
  <Route key="marine-mammals" path="/marine-mammals" element={<GenericSubcategoryPage />} />,
  <Route key="jellyfish-siphonophores" path="/jellyfish-siphonophores" element={<GenericSubcategoryPage />} />,
  <Route key="reptiles-snakes" path="/reptiles-snakes" element={<GenericSubcategoryPage />} />,
  <Route key="rodents" path="/rodents" element={<GenericSubcategoryPage />} />,
  <Route key="octopus-cephalopods" path="/octopus-cephalopods" element={<GenericSubcategoryPage />} />,
  <Route key="plants-flowers" path="/plants-flowers" element={<GenericSubcategoryPage />} />,
  <Route key="lakes" path="/lakes" element={<GenericSubcategoryPage />} />,
  <Route key="rivers" path="/rivers" element={<GenericSubcategoryPage />} />,
  <Route key="seas" path="/seas" element={<GenericSubcategoryPage />} />,
  
  // Crime & Justice flat routes
  <Route key="courts-indictment" path="/courts-indictment" element={<GenericSubcategoryPage />} />,
  <Route key="courts-sentencing" path="/courts-sentencing" element={<GenericSubcategoryPage />} />,
  <Route key="courts-police" path="/courts-police" element={<GenericSubcategoryPage />} />,
  <Route key="supreme-courts" path="/supreme-courts" element={<GenericSubcategoryPage />} />,
  <Route key="crime-fraud-scammers" path="/crime-fraud-scammers" element={<GenericSubcategoryPage />} />,
  <Route key="criminal-enterprises" path="/criminal-enterprises" element={<GenericSubcategoryPage />} />,
  <Route key="criminal-gangs" path="/criminal-gangs" element={<GenericSubcategoryPage />} />,
  <Route key="criminal-gangsters" path="/criminal-gangsters" element={<GenericSubcategoryPage />} />,
  <Route key="police-chases" path="/police-chases" element={<GenericSubcategoryPage />} />,
  <Route key="police-sheriff" path="/police-sheriff" element={<GenericSubcategoryPage />} />,
  <Route key="police-stops" path="/police-stops" element={<GenericSubcategoryPage />} />,
  <Route key="jails-prisons" path="/jails-prisons" element={<GenericSubcategoryPage />} />,
  <Route key="attorney-information" path="/attorney-information" element={<GenericSubcategoryPage />} />,
  
  // Business & Finance flat routes
  <Route key="stocks-commodities" path="/stocks-commodities" element={<GenericSubcategoryPage />} />,
  <Route key="bitcoin-cryptocurrency" path="/bitcoin-cryptocurrency" element={<GenericSubcategoryPage />} />,
  <Route key="business-development" path="/business-development" element={<GenericSubcategoryPage />} />,
  <Route key="business-leaders" path="/business-leaders" element={<GenericSubcategoryPage />} />,
  <Route key="money-taxes" path="/money-taxes" element={<GenericSubcategoryPage />} />,
  <Route key="business-services" path="/business-services" element={<GenericSubcategoryPage />} />,
  <Route key="farmers-farming" path="/farmers-farming" element={<GenericSubcategoryPage />} />,
  <Route key="real-estate-commercial" path="/real-estate-commercial" element={<GenericSubcategoryPage />} />,
  <Route key="luxury-real-estate" path="/luxury-real-estate" element={<GenericSubcategoryPage />} />,
  <Route key="food-products-business" path="/food-products-business" element={<GenericSubcategoryPage />} />,
  
  // Entertainment flat routes
  <Route key="oscars-golden-globes" path="/oscars-golden-globes" element={<GenericSubcategoryPage />} />,
  <Route key="actors-actresses" path="/actors-actresses" element={<GenericSubcategoryPage />} />,
  <Route key="late-night-shows" path="/late-night-shows" element={<GenericSubcategoryPage />} />,
  <Route key="entertainment-podcasts" path="/entertainment-podcasts" element={<GenericSubcategoryPage />} />,
  <Route key="hollywood-celebrities" path="/hollywood-celebrities" element={<GenericSubcategoryPage />} />,
  <Route key="auditions-contests" path="/auditions-contests" element={<GenericSubcategoryPage />} />,
  <Route key="tv-news-shows" path="/tv-news-shows" element={<GenericSubcategoryPage />} />,
  <Route key="radio-shows" path="/radio-shows" element={<GenericSubcategoryPage />} />,
  
  // Comedy flat routes
  <Route key="comedians-interviews" path="/comedians-interviews" element={<GenericSubcategoryPage />} />,
  <Route key="funny-pranks" path="/funny-pranks" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-roasts" path="/comedy-roasts" element={<GenericSubcategoryPage />} />,
  <Route key="snl" path="/snl" element={<GenericSubcategoryPage />} />,
  <Route key="stand-up-comedy" path="/stand-up-comedy" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-jokes-pranks" path="/comedy-jokes-pranks" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-sitcoms" path="/comedy-sitcoms" element={<GenericSubcategoryPage />} />,
  <Route key="bloopers" path="/bloopers" element={<GenericSubcategoryPage />} />,
  <Route key="funny-short-videos" path="/funny-short-videos" element={<GenericSubcategoryPage />} />,
  <Route key="funny-weird" path="/funny-weird" element={<GenericSubcategoryPage />} />,
  
  // Music flat routes
  <Route key="rock-soul" path="/rock-soul" element={<GenericSubcategoryPage />} />,
  <Route key="blues" path="/blues" element={<GenericSubcategoryPage />} />,
  <Route key="classical-opera" path="/classical-opera" element={<GenericSubcategoryPage />} />,
  <Route key="country-western" path="/country-western" element={<GenericSubcategoryPage />} />,
  <Route key="folk-music" path="/folk-music" element={<GenericSubcategoryPage />} />,
  <Route key="funk-hard-rock" path="/funk-hard-rock" element={<GenericSubcategoryPage />} />,
  <Route key="hip-hop-rap" path="/hip-hop-rap" element={<GenericSubcategoryPage />} />,
  <Route key="heavy-metal" path="/heavy-metal" element={<GenericSubcategoryPage />} />,
  <Route key="pop-rnb" path="/pop-rnb" element={<GenericSubcategoryPage />} />,
  <Route key="reggaeton" path="/reggaeton" element={<GenericSubcategoryPage />} />,
  <Route key="salsa" path="/salsa" element={<GenericSubcategoryPage />} />,
  <Route key="christian-music" path="/christian-music" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists" path="/music-artists" element={<GenericSubcategoryPage />} />,
  <Route key="music-lyrics" path="/music-lyrics" element={<GenericSubcategoryPage />} />,
  
  // Gaming flat routes
  <Route key="arcade-games" path="/arcade-games" element={<GenericSubcategoryPage />} />,
  <Route key="casino-slots" path="/casino-slots" element={<GenericSubcategoryPage />} />,
  <Route key="dominos" path="/dominos" element={<GenericSubcategoryPage />} />,
  <Route key="lottery" path="/lottery" element={<GenericSubcategoryPage />} />,
  <Route key="xbox-playstation" path="/xbox-playstation" element={<GenericSubcategoryPage />} />,
  <Route key="card-games" path="/card-games" element={<GenericSubcategoryPage />} />,
  <Route key="magic-tricks" path="/magic-tricks" element={<GenericSubcategoryPage />} />,
  <Route key="game-challenges" path="/game-challenges" element={<GenericSubcategoryPage />} />,
  
  // Fitness flat routes
  <Route key="calisthenics" path="/calisthenics" element={<GenericSubcategoryPage />} />,
  <Route key="weight-lifting" path="/weight-lifting" element={<GenericSubcategoryPage />} />,
  <Route key="yoga-workout" path="/yoga-workout" element={<GenericSubcategoryPage />} />,
  <Route key="workout-female" path="/workout-female" element={<GenericSubcategoryPage />} />,
  <Route key="workout-male" path="/workout-male" element={<GenericSubcategoryPage />} />,
  <Route key="martial-arts" path="/martial-arts" element={<GenericSubcategoryPage />} />,
  <Route key="swimming-diving" path="/swimming-diving" element={<GenericSubcategoryPage />} />,
  
  // Sports flat routes
  <Route key="nba-basketball" path="/nba-basketball" element={<GenericSubcategoryPage />} />,
  <Route key="nfl-football" path="/nfl-football" element={<GenericSubcategoryPage />} />,
  <Route key="mlb-baseball" path="/mlb-baseball" element={<GenericSubcategoryPage />} />,
  <Route key="nhl-hockey" path="/nhl-hockey" element={<GenericSubcategoryPage />} />,
  <Route key="soccer-mls" path="/soccer-mls" element={<GenericSubcategoryPage />} />,
  <Route key="mma-ufc" path="/mma-ufc" element={<GenericSubcategoryPage />} />,
  <Route key="tennis" path="/tennis" element={<GenericSubcategoryPage />} />,
  <Route key="golf" path="/golf" element={<GenericSubcategoryPage />} />,
  <Route key="olympics" path="/olympics" element={<GenericSubcategoryPage />} />,
  <Route key="nascar-racing" path="/nascar-racing" element={<GenericSubcategoryPage />} />,
  <Route key="formula-one" path="/formula-one" element={<GenericSubcategoryPage />} />,
  
  // Travel flat routes
  <Route key="beaches" path="/beaches" element={<GenericSubcategoryPage />} />,
  <Route key="cities-towns" path="/cities-towns" element={<GenericSubcategoryPage />} />,
  <Route key="hotels" path="/hotels" element={<GenericSubcategoryPage />} />,
  <Route key="night-clubs" path="/night-clubs" element={<GenericSubcategoryPage />} />,
  <Route key="street-food" path="/street-food" element={<GenericSubcategoryPage />} />,
  
  // Film flat routes
  <Route key="action-movies" path="/action-movies" element={<GenericSubcategoryPage />} />,
  <Route key="comedy-movies" path="/comedy-movies" element={<GenericSubcategoryPage />} />,
  <Route key="drama-movies" path="/drama-movies" element={<GenericSubcategoryPage />} />,
  <Route key="documentary-films" path="/documentary-films" element={<GenericSubcategoryPage />} />,
  <Route key="cartoons" path="/cartoons" element={<GenericSubcategoryPage />} />,
  
  // Education flat routes
  <Route key="kids-education" path="/kids-education" element={<GenericSubcategoryPage />} />,
  <Route key="history" path="/history" element={<GenericSubcategoryPage />} />,
  <Route key="science" path="/science" element={<GenericSubcategoryPage />} />,
  
  // News flat routes
  <Route key="politics" path="/politics" element={<GenericSubcategoryPage />} />,

  // ========== NESTED SPORTS ROUTES (for sidebar links) ==========
  // College sports nested routes
  <Route key="sports-college-nested" path="/sports/college" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-football-nested" path="/sports/college/football" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-basketball-nested" path="/sports/college/basketball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-baseball-nested" path="/sports/college/baseball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-women-basketball-nested" path="/sports/college/women-basketball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-swimming-nested" path="/sports/college/swimming" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-track-nested" path="/sports/college/track" element={<GenericSubcategoryPage />} />,
  <Route key="sports-college-bowl-nested" path="/sports/college/bowl" element={<GenericSubcategoryPage />} />,

  // NBA nested routes
  <Route key="sports-nba-east-playoffs" path="/sports/nba/east-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nba-west-playoffs" path="/sports/nba/west-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nba-players" path="/sports/nba/players" element={<GenericSubcategoryPage />} />,

  // NFL nested routes
  <Route key="sports-nfl-superbowl-nested" path="/sports/nfl/superbowl" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nfl-players" path="/sports/nfl/players" element={<GenericSubcategoryPage />} />,

  // MLB nested routes
  <Route key="sports-mlb-al-playoffs" path="/sports/mlb/al-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mlb-nl-playoffs" path="/sports/mlb/nl-playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mlb-world-series" path="/sports/mlb/world-series" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mlb-players" path="/sports/mlb/players" element={<GenericSubcategoryPage />} />,

  // NHL nested routes
  <Route key="sports-nhl-allstar-nested" path="/sports/nhl/allstar" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl-east" path="/sports/nhl/east" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl-west" path="/sports/nhl/west" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl-playoffs-nested" path="/sports/nhl/playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-nhl-players" path="/sports/nhl/players" element={<GenericSubcategoryPage />} />,

  // WNBA nested routes
  <Route key="sports-wnba-players" path="/sports/wnba/players" element={<GenericSubcategoryPage />} />,
  <Route key="sports-wnba-playoffs-nested" path="/sports/wnba/playoffs" element={<GenericSubcategoryPage />} />,
  <Route key="sports-wnba-championship" path="/sports/wnba/championship" element={<GenericSubcategoryPage />} />,

  // MMA nested routes
  <Route key="sports-mma-ufc" path="/sports/mma/ufc" element={<GenericSubcategoryPage />} />,
  <Route key="sports-mma-women" path="/sports/mma/women" element={<GenericSubcategoryPage />} />,
  <Route key="sports-boxing-interviews-nested" path="/sports/boxing/interviews" element={<GenericSubcategoryPage />} />,
  <Route key="sports-wrestling" path="/sports/wrestling" element={<GenericSubcategoryPage />} />,

  // Racing routes
  <Route key="sports-racing" path="/sports/racing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-motorcycle-racing" path="/sports/motorcycle-racing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-racing-track" path="/sports/racing-track" element={<GenericSubcategoryPage />} />,

  // Tennis nested routes
  <Route key="sports-tennis" path="/sports/tennis" element={<GenericSubcategoryPage />} />,
  <Route key="sports-tennis-men-nested" path="/sports/tennis/men" element={<GenericSubcategoryPage />} />,
  <Route key="sports-tennis-women-nested" path="/sports/tennis/women" element={<GenericSubcategoryPage />} />,
  <Route key="sports-tennis-men-finals" path="/sports/tennis/men-finals" element={<GenericSubcategoryPage />} />,
  <Route key="sports-tennis-women-finals" path="/sports/tennis/women-finals" element={<GenericSubcategoryPage />} />,

  // Golf nested routes
  <Route key="sports-golf" path="/sports/golf" element={<GenericSubcategoryPage />} />,
  <Route key="sports-ryder-cup" path="/sports/ryder-cup" element={<GenericSubcategoryPage />} />,

  // Olympics nested routes
  <Route key="sports-olympics-track" path="/sports/olympics/track" element={<GenericSubcategoryPage />} />,

  // Volleyball nested routes
  <Route key="sports-volleyball-amateur" path="/sports/volleyball/amateur" element={<GenericSubcategoryPage />} />,
  <Route key="sports-volleyball-beach" path="/sports/volleyball/beach" element={<GenericSubcategoryPage />} />,
  <Route key="sports-volleyball-pro" path="/sports/volleyball/pro" element={<GenericSubcategoryPage />} />,
  <Route key="sports-volleyball-tournament" path="/sports/volleyball/tournament" element={<GenericSubcategoryPage />} />,

  // Water sports nested routes
  <Route key="sports-water" path="/sports/water" element={<GenericSubcategoryPage />} />,
  <Route key="sports-swimming" path="/sports/swimming" element={<GenericSubcategoryPage />} />,
  <Route key="sports-diving" path="/sports/diving" element={<GenericSubcategoryPage />} />,

  // Swim nested routes
  <Route key="swim-diving" path="/swim/diving" element={<GenericSubcategoryPage />} />,
  <Route key="swim-plunge" path="/swim/plunge" element={<GenericSubcategoryPage />} />,
  <Route key="swim-plummet" path="/swim/plummet" element={<GenericSubcategoryPage />} />,
  <Route key="swim-jump" path="/swim/jump" element={<GenericSubcategoryPage />} />,
  <Route key="swim-freestyle" path="/swim/freestyle" element={<GenericSubcategoryPage />} />,

  // Other sports nested routes
  <Route key="sports-other" path="/sports/other" element={<GenericSubcategoryPage />} />,
  <Route key="sports-horses" path="/sports/horses" element={<GenericSubcategoryPage />} />,
  <Route key="sports-fans" path="/sports/fans" element={<GenericSubcategoryPage />} />,

  // ========== ADDITIONAL MISSING SIDEBAR ROUTES ==========
  
  // News & Politics nested routes
  <Route key="news" path="/news" element={<GenericSubcategoryPage />} />,
  <Route key="news-breaking" path="/news/breaking" element={<GenericSubcategoryPage />} />,
  <Route key="news-politics" path="/news/politics" element={<GenericSubcategoryPage />} />,
  <Route key="news-world" path="/news/world" element={<GenericSubcategoryPage />} />,
  <Route key="news-local" path="/news/local" element={<GenericSubcategoryPage />} />,
  <Route key="news-shows" path="/news/shows" element={<GenericSubcategoryPage />} />,
  <Route key="news-podcasts" path="/news/podcasts" element={<GenericSubcategoryPage />} />,
  
  // Senate & House nested routes
  <Route key="senate" path="/senate" element={<GenericSubcategoryPage />} />,
  <Route key="senate-house" path="/senate/house" element={<GenericSubcategoryPage />} />,
  <Route key="senate-sessions" path="/senate/sessions" element={<GenericSubcategoryPage />} />,
  
  // Protesters nested routes
  <Route key="protesters-demonstrators" path="/protesters/demonstrators" element={<GenericSubcategoryPage />} />,
  <Route key="protesters-rallies" path="/protesters/rallies" element={<GenericSubcategoryPage />} />,
  
  // Speeches nested routes (additional)
  <Route key="speeches-arguments" path="/speeches/arguments" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-commencement" path="/speeches/commencement" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-eulogy" path="/speeches/eulogy" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-informative" path="/speeches/informative" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-motivational" path="/speeches/motivational" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-persuasive" path="/speeches/persuasive" element={<GenericSubcategoryPage />} />,
  <Route key="speeches-motivation" path="/speeches/motivation" element={<GenericSubcategoryPage />} />,
  
  // Journalist nested routes
  <Route key="journalist" path="/journalist" element={<GenericSubcategoryPage />} />,
  <Route key="journalist-correspondent" path="/journalist/correspondent" element={<GenericSubcategoryPage />} />,
  
  // Mammals nested routes
  <Route key="mammals-primates" path="/mammals/primates" element={<GenericSubcategoryPage />} />,
  <Route key="mammals-carnivores" path="/mammals/carnivores" element={<GenericSubcategoryPage />} />,
  <Route key="mammals-rodents" path="/mammals/rodents" element={<GenericSubcategoryPage />} />,
  <Route key="mammals-marine-mammals" path="/mammals/marine-mammals" element={<GenericSubcategoryPage />} />,
  <Route key="mammals-marsupials" path="/mammals/marsupials" element={<GenericSubcategoryPage />} />,
  <Route key="mammals-bats" path="/mammals/bats" element={<GenericSubcategoryPage />} />,
  <Route key="mammals-elephants" path="/mammals/elephants" element={<GenericSubcategoryPage />} />,
  <Route key="mammals-ungulates" path="/mammals/ungulates" element={<GenericSubcategoryPage />} />,
  
  // Non-Mammals nested routes
  <Route key="non-mammals" path="/non-mammals" element={<GenericSubcategoryPage />} />,
  <Route key="non-mammals-fish" path="/non-mammals/fish" element={<GenericSubcategoryPage />} />,
  <Route key="non-mammals-birds" path="/non-mammals/birds" element={<GenericSubcategoryPage />} />,
  <Route key="non-mammals-reptiles" path="/non-mammals/reptiles" element={<GenericSubcategoryPage />} />,
  <Route key="non-mammals-amphibians" path="/non-mammals/amphibians" element={<GenericSubcategoryPage />} />,
  <Route key="non-mammals-arthropods" path="/non-mammals/arthropods" element={<GenericSubcategoryPage />} />,
  <Route key="non-mammals-mollusks" path="/non-mammals/mollusks" element={<GenericSubcategoryPage />} />,
  <Route key="non-mammals-echinoderms" path="/non-mammals/echinoderms" element={<GenericSubcategoryPage />} />,
  <Route key="non-mammals-invertebrates" path="/non-mammals/invertebrates" element={<GenericSubcategoryPage />} />,
  
  // Travel & Events additional nested routes
  <Route key="travel-country-foods" path="/travel/country-foods" element={<GenericSubcategoryPage />} />,
  <Route key="travel-hotels-expensive" path="/travel/hotels-expensive" element={<GenericSubcategoryPage />} />,
  <Route key="travel-hotels-unique" path="/travel/hotels-unique" element={<GenericSubcategoryPage />} />,
  <Route key="travel-nightlife" path="/travel/nightlife" element={<GenericSubcategoryPage />} />,
  
  // Beaches nested routes
  <Route key="beaches-tropical" path="/beaches/tropical" element={<GenericSubcategoryPage />} />,
  <Route key="beaches-surfing" path="/beaches/surfing" element={<GenericSubcategoryPage />} />,
  <Route key="beaches-resorts" path="/beaches/resorts" element={<GenericSubcategoryPage />} />,
  
  // Airports additional nested routes
  <Route key="airports-security" path="/airports/security" element={<GenericSubcategoryPage />} />,
  <Route key="airports-lounges" path="/airports/lounges" element={<GenericSubcategoryPage />} />,
  
  // Restaurants additional nested routes
  <Route key="restaurants-reviews" path="/restaurants/reviews" element={<GenericSubcategoryPage />} />,
  <Route key="restaurants-celebrity-chefs" path="/restaurants/celebrity-chefs" element={<GenericSubcategoryPage />} />,
  
  // Hollywood nested routes (from sidebar)
  <Route key="hollywood-bios" path="/hollywood/bios" element={<GenericSubcategoryPage />} />,
  <Route key="hollywood-news" path="/hollywood/news" element={<GenericSubcategoryPage />} />,
  <Route key="hollywood-interviews" path="/hollywood/interviews" element={<GenericSubcategoryPage />} />,
  
  // Music additional nested routes
  <Route key="music-hiphop" path="/music/hiphop" element={<GenericSubcategoryPage />} />,
  <Route key="music-heavy-metal" path="/music/heavy-metal" element={<GenericSubcategoryPage />} />,
  <Route key="music-rnb" path="/music/rnb" element={<GenericSubcategoryPage />} />,
  <Route key="music-history" path="/music/history" element={<GenericSubcategoryPage />} />,
  <Route key="music-international" path="/music/international" element={<GenericSubcategoryPage />} />,
  <Route key="music-mandopop" path="/music/mandopop" element={<GenericSubcategoryPage />} />,
  <Route key="music-latin" path="/music/latin" element={<GenericSubcategoryPage />} />,
  <Route key="music-lyrics" path="/music/lyrics" element={<GenericSubcategoryPage />} />,
  <Route key="music-lyrics-mandopop" path="/music/lyrics/mandopop" element={<GenericSubcategoryPage />} />,
  <Route key="music-lyrics-spanish" path="/music/lyrics/spanish" element={<GenericSubcategoryPage />} />,
  <Route key="music-artists-challenges" path="/music-artists/challenges" element={<GenericSubcategoryPage />} />,
  <Route key="music-instruments-nested" path="/music/instruments" element={<GenericSubcategoryPage />} />,
  <Route key="music-instruments-players" path="/music/instruments/players" element={<GenericSubcategoryPage />} />,
  
  // Stocks nested routes
  <Route key="stocks-news" path="/stocks/news" element={<GenericSubcategoryPage />} />,
  <Route key="stocks-crypto" path="/stocks/crypto" element={<GenericSubcategoryPage />} />,
  
  // Cryptocurrency routes
  <Route key="cryptocurrency" path="/cryptocurrency" element={<GenericSubcategoryPage />} />,
  <Route key="cryptocurrency-bitcoin" path="/cryptocurrency/bitcoin" element={<GenericSubcategoryPage />} />,
  <Route key="cryptocurrency-ethereum" path="/cryptocurrency/ethereum" element={<GenericSubcategoryPage />} />,
  <Route key="cryptocurrency-news" path="/cryptocurrency/news" element={<GenericSubcategoryPage />} />,
  <Route key="cryptocurrency-trading" path="/cryptocurrency/trading" element={<GenericSubcategoryPage />} />,
  
  // AI routes (additional)
  <Route key="ai-news" path="/ai/news" element={<GenericSubcategoryPage />} />,
  <Route key="ai-tutorials" path="/ai/tutorials" element={<GenericSubcategoryPage />} />,
  <Route key="ai-products" path="/ai/products" element={<GenericSubcategoryPage />} />,
  
  // Radio additional routes
  <Route key="radio-news" path="/radio/news" element={<GenericSubcategoryPage />} />,
  
  // Missing travel routes from sidebar
  <Route key="travel-country-foods" path="/travel/country-foods" element={<GenericSubcategoryPage />} />,
  <Route key="travel-hotels-expensive" path="/travel/hotels-expensive" element={<GenericSubcategoryPage />} />,
  <Route key="travel-hotels-unique" path="/travel/hotels-unique" element={<GenericSubcategoryPage />} />,
  <Route key="travel-nightlife" path="/travel/nightlife" element={<GenericSubcategoryPage />} />,
  
  // Missing film routes from sidebar
  <Route key="film-action-crime" path="/film/action-crime" element={<GenericSubcategoryPage />} />,
  <Route key="film-comedy-drama" path="/film/comedy-drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-crime-drama" path="/film/crime-drama" element={<GenericSubcategoryPage />} />,
  <Route key="film-clips" path="/film/clips" element={<GenericSubcategoryPage />} />,
  
  // Missing entertainment routes from sidebar
  <Route key="entertainment-podcast" path="/entertainment/podcast" element={<GenericSubcategoryPage />} />,
  
  // Missing music routes from sidebar (grunge categories)
  <Route key="music-grunge-nested" path="/music/grunge" element={<GenericSubcategoryPage />} />,
  <Route key="music-rock-grunge" path="/music/rock-grunge" element={<GenericSubcategoryPage />} />,
  <Route key="music-alternative-grunge" path="/music/alternative-grunge" element={<GenericSubcategoryPage />} />,
  <Route key="music-classic-grunge" path="/music/classic-grunge" element={<GenericSubcategoryPage />} />,
  <Route key="music-post-grunge" path="/music/post-grunge" element={<GenericSubcategoryPage />} />,
  <Route key="music-funk-nested" path="/music/funk" element={<GenericSubcategoryPage />} />,
  <Route key="music-rap-nested" path="/music/rap" element={<GenericSubcategoryPage />} />,
  
  // Missing travel-events route
  <Route key="travel-events" path="/travel-events" element={<GenericSubcategoryPage />} />,
  
  // ========== FITNESS & HEALTH MISSING ROUTES ==========
  // Fitness nested routes from sidebar
  <Route key="fitness" path="/fitness" element={<GenericSubcategoryPage />} />,
  <Route key="fitness-calisthenics" path="/fitness/calisthenics" element={<GenericSubcategoryPage />} />,
  <Route key="fitness-weightlifting-prank" path="/fitness/weightlifting-prank" element={<GenericSubcategoryPage />} />,
  <Route key="fitness-weightlifting-female" path="/fitness/weightlifting-female" element={<GenericSubcategoryPage />} />,
  <Route key="fitness-weightlifting-male" path="/fitness/weightlifting-male" element={<GenericSubcategoryPage />} />,
  <Route key="fitness-workout" path="/fitness/workout" element={<GenericSubcategoryPage />} />,
  <Route key="fitness-workout-female" path="/fitness/workout-female" element={<GenericSubcategoryPage />} />,
  <Route key="fitness-workout-male" path="/fitness/workout-male" element={<GenericSubcategoryPage />} />,
  <Route key="fitness-yoga" path="/fitness/yoga" element={<GenericSubcategoryPage />} />,
  
  // Martial Arts nested routes from sidebar
  <Route key="martial-arts-training" path="/martial-arts/training" element={<GenericSubcategoryPage />} />,
  
  // Health nested routes from sidebar
  <Route key="health" path="/health" element={<GenericSubcategoryPage />} />,
  <Route key="health-reproductive" path="/health/reproductive" element={<GenericSubcategoryPage />} />,
  <Route key="health-mental" path="/health/mental" element={<GenericSubcategoryPage />} />,
  
  // Meditation nested routes from sidebar
  <Route key="meditation-guided" path="/meditation/guided" element={<GenericSubcategoryPage />} />,
  <Route key="meditation-sleep" path="/meditation/sleep" element={<GenericSubcategoryPage />} />,
  
  // Success nested routes from sidebar
  <Route key="success" path="/success" element={<GenericSubcategoryPage />} />,
  <Route key="success-achieve" path="/success/achieve" element={<GenericSubcategoryPage />} />,
  <Route key="success-motivation" path="/success/motivation" element={<GenericSubcategoryPage />} />,
  
  // ========== GAMING & HOBBIES MISSING ROUTES ==========
  <Route key="gaming-xbox" path="/gaming/xbox" element={<GenericSubcategoryPage />} />,
  <Route key="magic-tricks-card" path="/magic-tricks/card" element={<GenericSubcategoryPage />} />,
  <Route key="game-challenges" path="/game-challenges" element={<GenericSubcategoryPage />} />,
  <Route key="game-challenges-toys" path="/game-challenges/toys" element={<GenericSubcategoryPage />} />,
  <Route key="game-challenges-experiments" path="/game-challenges/experiments" element={<GenericSubcategoryPage />} />,
  <Route key="riddles-conundrum" path="/riddles/conundrum" element={<GenericSubcategoryPage />} />,
  
  // ========== TRANSPORT & VEHICLES MISSING ROUTES ==========
  <Route key="autos-vehicles" path="/autos-vehicles" element={<GenericSubcategoryPage />} />,
  <Route key="autos-vehicles-supercars" path="/autos-vehicles/supercars" element={<GenericSubcategoryPage />} />,
  <Route key="autos-vehicles-expensive-cars" path="/autos-vehicles/expensive-cars" element={<GenericSubcategoryPage />} />,
  <Route key="autos-vehicles-car-repairs" path="/autos-vehicles/car-repairs" element={<GenericSubcategoryPage />} />,
  <Route key="autos-vehicles-car-hacks" path="/autos-vehicles/car-hacks" element={<GenericSubcategoryPage />} />,
  <Route key="trains-railroad" path="/trains/railroad" element={<GenericSubcategoryPage />} />,
  <Route key="trains-railway" path="/trains/railway" element={<GenericSubcategoryPage />} />,
  <Route key="trains-steam" path="/trains/steam" element={<GenericSubcategoryPage />} />,
  <Route key="trains-freight" path="/trains/freight" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-cargo-ships" path="/shipping/cargo-ships" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-oil-tankers" path="/shipping/oil-tankers" element={<GenericSubcategoryPage />} />,
  <Route key="boats-all" path="/boats/all" element={<GenericSubcategoryPage />} />,
  <Route key="boats-sailboats" path="/boats/sailboats" element={<GenericSubcategoryPage />} />,
  <Route key="boats-speedboats" path="/boats/speedboats" element={<GenericSubcategoryPage />} />,
  
  // ========== ENVIRONMENT & WEATHER MISSING ROUTES ==========
  <Route key="weather-forecast" path="/weather/forecast" element={<GenericSubcategoryPage />} />,
  <Route key="weather-climate" path="/weather/climate" element={<GenericSubcategoryPage />} />,
  <Route key="weather-extreme" path="/weather/extreme" element={<GenericSubcategoryPage />} />,
  <Route key="disasters-landslides" path="/disasters/landslides" element={<GenericSubcategoryPage />} />,
  <Route key="engineering-disasters-civil" path="/engineering-disasters/civil" element={<GenericSubcategoryPage />} />,
  <Route key="engineering-disasters-mechanical" path="/engineering-disasters/mechanical" element={<GenericSubcategoryPage />} />,
  <Route key="engineering-disasters-electrical" path="/engineering-disasters/electrical" element={<GenericSubcategoryPage />} />,
  <Route key="engineering-disasters-chemical" path="/engineering-disasters/chemical" element={<GenericSubcategoryPage />} />,
  <Route key="floods-flash-flood" path="/floods/flash-flood" element={<GenericSubcategoryPage />} />,
  <Route key="floods-deluge" path="/floods/deluge" element={<GenericSubcategoryPage />} />,
  <Route key="floods-downpour" path="/floods/downpour" element={<GenericSubcategoryPage />} />,
  <Route key="floods-drown" path="/floods/drown" element={<GenericSubcategoryPage />} />,
  <Route key="floods-engulf" path="/floods/engulf" element={<GenericSubcategoryPage />} />,
  <Route key="floods-stream" path="/floods/stream" element={<GenericSubcategoryPage />} />,
  <Route key="oceans-marine-life" path="/oceans/marine-life" element={<GenericSubcategoryPage />} />,
  <Route key="oceans-deep-sea" path="/oceans/deep-sea" element={<GenericSubcategoryPage />} />,
  <Route key="oceans-coral-reefs" path="/oceans/coral-reefs" element={<GenericSubcategoryPage />} />,
  <Route key="oceans-exploration" path="/oceans/exploration" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-ports" path="/shipping-ports" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-ports-cargo" path="/shipping-ports/cargo" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-ports-cruise" path="/shipping-ports/cruise" element={<GenericSubcategoryPage />} />,
  <Route key="shipping-ports-history" path="/shipping-ports/history" element={<GenericSubcategoryPage />} />,
  
  // ========== FOOD & DRINKS MISSING ROUTES ==========
  <Route key="foods-tuna" path="/foods/tuna" element={<GenericSubcategoryPage />} />,
  <Route key="foods-weight-gain" path="/foods/weight-gain" element={<GenericSubcategoryPage />} />,
  
  // ========== BEACHES MISSING ROUTES ==========
  <Route key="beaches" path="/beaches" element={<GenericSubcategoryPage />} />,
  
  // ========== FILM & ANIMATION MISSING ROUTES ==========
  <Route key="film-animation-movies" path="/film-animation/movies" element={<GenericSubcategoryPage />} />,
  <Route key="film-horror" path="/film/horror" element={<GenericSubcategoryPage />} />,
  <Route key="film-horror-terror" path="/film/horror/terror" element={<GenericSubcategoryPage />} />,
  <Route key="film-horror-fear" path="/film/horror/fear" element={<GenericSubcategoryPage />} />,
  <Route key="film-horror-fright" path="/film/horror/fright" element={<GenericSubcategoryPage />} />,
  <Route key="film-horror-dread" path="/film/horror/dread" element={<GenericSubcategoryPage />} />,
  <Route key="film-horror-slasher" path="/film/horror/slasher" element={<GenericSubcategoryPage />} />,
  <Route key="film-spaghetti-westerns" path="/film/spaghetti-westerns" element={<GenericSubcategoryPage />} />,
  <Route key="film-modern-westerns" path="/film/modern-westerns" element={<GenericSubcategoryPage />} />,
  <Route key="film-western-comedies" path="/film/western-comedies" element={<GenericSubcategoryPage />} />,
  <Route key="film-neo-westerns" path="/film/neo-westerns" element={<GenericSubcategoryPage />} />,
  <Route key="film-acid-westerns" path="/film/acid-westerns" element={<GenericSubcategoryPage />} />,
  
  // ========== SWIM MAIN ROUTE ==========
  <Route key="swim" path="/swim" element={<GenericSubcategoryPage />} />,
  
  // ========== SPORTS MISSING ROUTES ==========
  <Route key="sports-mma" path="/sports/mma" element={<GenericSubcategoryPage />} />,
  <Route key="sports-volleyball" path="/sports/volleyball" element={<GenericSubcategoryPage />} />,
  <Route key="sports-kickboxing" path="/sports/kickboxing" element={<GenericSubcategoryPage />} />,
  <Route key="sports-pga" path="/sports/pga" element={<GenericSubcategoryPage />} />,
  <Route key="sports-arenas" path="/sports/arenas" element={<GenericSubcategoryPage />} />,
  <Route key="sports-comedy" path="/sports/comedy" element={<GenericSubcategoryPage />} />,
  <Route key="sports-interviews" path="/sports/interviews" element={<GenericSubcategoryPage />} />,
  <Route key="sports-weightlifting" path="/sports/weightlifting" element={<GenericSubcategoryPage />} />,
  <Route key="sports-track-field" path="/sports/track-field" element={<GenericSubcategoryPage />} />,
];

