import { useParams, Navigate } from "react-router-dom";

/**
 * Handles legacy/external URL pattern: /v/:id/:slug
 * These links come from outside scrapers/aggregators (not generated by miytube).
 * Convert the slug back to a search query so the visitor lands on relevant content
 * instead of a 404.
 */
const LegacyVideoRedirect = () => {
  const { slug } = useParams<{ id: string; slug: string }>();
  const query = (slug || "")
    .replace(/-+/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  if (!query) return <Navigate to="/" replace />;
  return <Navigate to={`/search?q=${encodeURIComponent(query)}`} replace />;
};

export default LegacyVideoRedirect;
