
import { Discussion } from './DiscussionCard';

// Modified mock data for discussions about world events and personal impact
export const INITIAL_DISCUSSIONS: Discussion[] = [
  {
    id: 1,
    category: 'Politics',
    title: 'How new privacy laws affect your digital life',
    author: 'PrivacyAdvocate',
    content: 'With the recent privacy legislation changes, I\'ve had to adjust how I use social media. Has anyone else changed their online habits?',
    replies: 15,
    likes: 28,
    timestamp: '2 hours ago',
  },
  {
    id: 2,
    category: 'Economy',
    title: 'Rising inflation and your monthly budget',
    author: 'BudgetPlanner',
    content: 'I\'ve noticed my grocery bills increasing by about 20% this year. What strategies are you using to manage your household expenses?',
    replies: 22,
    likes: 47,
    timestamp: '4 hours ago',
  },
  {
    id: 3,
    category: 'Climate',
    title: 'Local effects of global warming in your area',
    author: 'ClimateWatcher',
    content: 'Our city experienced unusual flooding this spring. Have you noticed climate change affecting your local environment?',
    replies: 43,
    likes: 86,
    timestamp: '8 hours ago',
  },
  {
    id: 4,
    category: 'Technology',
    title: 'How AI is changing your work environment',
    author: 'TechObserver',
    content: 'My company just implemented AI tools for customer service. Has anyone\'s job been significantly altered by new tech?',
    replies: 31,
    likes: 52,
    timestamp: '1 day ago',
  },
  {
    id: 5,
    category: 'Health',
    title: 'Global health trends affecting your community',
    author: 'HealthAdvocate',
    content: 'After the pandemic, our community is much more conscious about public health. What lasting changes have you seen in your area?',
    replies: 48,
    likes: 103,
    timestamp: '2 days ago',
  },
  {
    id: 6,
    category: 'Money',
    title: 'Best budgeting apps and methods that actually work',
    author: 'SavvySaver',
    content: 'I switched to the 50/30/20 budgeting method and it changed my financial life. What budgeting strategies have worked for you?',
    replies: 34,
    likes: 72,
    timestamp: '3 hours ago',
  },
  {
    id: 7,
    category: 'Money',
    title: 'Building an emergency fund in tough times',
    author: 'FinanceFirst',
    content: 'Started with just $25 a week and now have 3 months of expenses saved. How are you building your safety net?',
    replies: 28,
    likes: 65,
    timestamp: '6 hours ago',
  },
  {
    id: 8,
    category: 'Money',
    title: 'Index funds vs individual stocks for beginners',
    author: 'InvestorNewbie',
    content: 'Finally started investing at 30. Going with index funds for now. What investment strategies do you recommend for beginners?',
    replies: 41,
    likes: 89,
    timestamp: '1 day ago',
  },
  {
    id: 9,
    category: 'Music',
    title: 'The grunge revival - is it happening?',
    author: 'SeattleSound',
    content: 'Seeing so many new bands with that classic grunge sound. Nirvana, Pearl Jam vibes are back. What new grunge bands are you listening to?',
    replies: 26,
    likes: 58,
    timestamp: '5 hours ago',
  },
  {
    id: 10,
    category: 'Music',
    title: 'Best alternative rock albums of the decade',
    author: 'AltRocker',
    content: 'From Radiohead to Arctic Monkeys, alternative rock keeps evolving. What are your top picks for must-listen albums?',
    replies: 52,
    likes: 94,
    timestamp: '12 hours ago',
  },
  {
    id: 11,
    category: 'Music',
    title: 'Classic rock vs modern rock - the endless debate',
    author: 'RockLegend',
    content: 'Led Zeppelin or Foo Fighters? Can modern rock ever match the classics? Let\'s discuss the evolution of rock music.',
    replies: 67,
    likes: 112,
    timestamp: '1 day ago',
  },
];

// Updated categories to focus on world events and personal impact
export const CATEGORIES = [
  'All Categories',
  'Artificial Intelligence',
  'Business',
  'Climate',
  'Cryptocurrencies',
  'Culture',
  'Economy',
  'Education',
  'Entertainment',
  'Health',
  'Money',
  'Music',
  'News',
  'Politics',
  'Stocks',
  'Technology',
];
